/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerInventario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo Perdomo
 */
public class FrmViewVerInventario extends javax.swing.JInternalFrame {

    private final ControllerInventario controlInventario;
    DefaultTableModel modeloTablaProductos = new DefaultTableModel();
    /**
     * Creates new form FrmViewVerInventario
     */
    public FrmViewVerInventario() {
        controlInventario = new ControllerInventario();
        initComponents();
        refrescarInventario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInventario = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Inventario");

        tableInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableInventario.setEnabled(false);
        jScrollPane1.setViewportView(tableInventario);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/recargar-inventario-24px.png"))); // NOI18N
        jButton1.setToolTipText("Refrescar Inventario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(478, 478, 478))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        refrescarInventario();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void refrescarInventario() {
        //Se establecen los elementos de la cabecera de la tabla
        String[] cabeceraProducto = {"ID", "Nombre", "Unidad de Medida", "Precio", "Cantidad", "ID Proveedor", "Descripcion"};
        //Se recogen los datos de los clientes añadidos en el almacenamiento temporal
        String[][] matrizProducto = controlInventario.refrescarTablaInventario();
        //Se agregan los datos y la cabecera de la tabla al modelo
        modeloTablaProductos.setDataVector(matrizProducto, cabeceraProducto);
        //Se agrega el modelo a la vista
        tableInventario.setModel(modeloTablaProductos);
        if (tableInventario.getColumnModel().getColumnCount() > 0) {
            tableInventario.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableInventario.getColumnModel().getColumn(1).setPreferredWidth(200);
            tableInventario.getColumnModel().getColumn(6).setPreferredWidth(300);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableInventario;
    // End of variables declaration//GEN-END:variables
}
