/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.EstadoPedido;
import Controller.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicLabelUI;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author Leonardo Perdomo
 */
public class FrmViewTerceros2 extends javax.swing.JInternalFrame {

    private CardLayout cardLayout;
    private final ControllerCliente controlCliente;
    private final ControllerVendedor controlVendedor;
    private final ControllerProveedor controlProveedor;
    private Date fecha;

    DefaultTableModel modeloTablaPersona = new DefaultTableModel();

    /**
     * Creates new form FrmViewTerceros2
     */
    public FrmViewTerceros2() {

        controlCliente = new ControllerCliente();
        controlVendedor = new ControllerVendedor();
        controlProveedor = new ControllerProveedor();
        fecha = new Date();

        initComponents();

        // Se declaran componentes para hacer funcionar el splipanel
        Component[] components = this.getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JLabel) {
                ((JLabel) component).setUI(new BasicLabelUI());
                ((JLabel) component).setFocusCycleRoot(false);
            }

        }
        cardLayout = (CardLayout) (panelCards.getLayout());

        String persona = cBoxTipoPersonaCrear.getSelectedItem().toString();
        switch (persona) {
            case "Cliente" -> {
                textFieldIDCrear.setText(controlCliente.obtenerId(persona, persona + "s".toLowerCase()));
            }
            case "Vendedor" -> {
                textFieldIDCrear.setText(controlCliente.obtenerId(persona, persona + "es".toLowerCase()));
            }
            case "Proveedor" -> {
                textFieldIDCrear.setText(controlCliente.obtenerId(persona, persona + "es".toLowerCase()));
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelLateral = new javax.swing.JPanel();
        labelCrear = new javax.swing.JLabel();
        labelBuscar = new javax.swing.JLabel();
        labelRegistros = new javax.swing.JLabel();
        panelCards = new javax.swing.JPanel();
        panelCrear = new javax.swing.JPanel();
        labelTipoPersonaCrear = new javax.swing.JLabel();
        cBoxTipoPersonaCrear = new javax.swing.JComboBox<>();
        labelIDCrear = new javax.swing.JLabel();
        labelDireccionCrear = new javax.swing.JLabel();
        labelCorreoCrear = new javax.swing.JLabel();
        labelDepartamentoCrear = new javax.swing.JLabel();
        labelNoDocumentoCrear = new javax.swing.JLabel();
        textFieldIDCrear = new javax.swing.JTextField();
        textFieldDireccionCrear = new javax.swing.JTextField();
        textFieldCorreoCrear = new javax.swing.JTextField();
        textFieldDepartamentoCrear = new javax.swing.JTextField();
        textFieldNoDocumentoCrear = new javax.swing.JTextField();
        labelNombreCrear = new javax.swing.JLabel();
        labelTelefonoCrear = new javax.swing.JLabel();
        labelCiudadCrear = new javax.swing.JLabel();
        labelFechaNacimientoCrear = new javax.swing.JLabel();
        labelTipoDocumentoCrear = new javax.swing.JLabel();
        textFieldCiudadCrear = new javax.swing.JTextField();
        textFieldTelefonoCrear = new javax.swing.JTextField();
        textFieldNombreCrear = new javax.swing.JTextField();
        rButtonCCCrear = new javax.swing.JRadioButton();
        rButtonNitCrear = new javax.swing.JRadioButton();
        rButtonOtroCrear = new javax.swing.JRadioButton();
        btnCrear = new javax.swing.JButton();
        labelTituloCrear = new javax.swing.JLabel();
        dateChooserFechaNacimientoCrear = new com.toedter.calendar.JDateChooser();
        panelBuscar = new javax.swing.JPanel();
        labelTipoPersonaBuscar = new javax.swing.JLabel();
        cBoxTipoPersonaBuscar = new javax.swing.JComboBox<>();
        labelIDBuscar = new javax.swing.JLabel();
        labelDireccionBuscar = new javax.swing.JLabel();
        labelCorreoBuscar = new javax.swing.JLabel();
        labelDepartamentoBuscar = new javax.swing.JLabel();
        labelNoDocumentoBuscar = new javax.swing.JLabel();
        textFieldIDBuscar = new javax.swing.JTextField();
        textFieldDireccionBuscar = new javax.swing.JTextField();
        textFieldCorreoBuscar = new javax.swing.JTextField();
        textFieldDepartamentoBuscar = new javax.swing.JTextField();
        textFieldNoDocumentoBuscar = new javax.swing.JTextField();
        labelNombreBuscar = new javax.swing.JLabel();
        labelTelefonoBuscar = new javax.swing.JLabel();
        labelCiudadBuscar = new javax.swing.JLabel();
        labelFechaBuscar = new javax.swing.JLabel();
        labelTipoDocumentoBuscar = new javax.swing.JLabel();
        textFieldFechaBuscar = new javax.swing.JTextField();
        textFieldCiudadBuscar = new javax.swing.JTextField();
        textFieldTelefonoBuscar = new javax.swing.JTextField();
        textFieldNombreBuscar = new javax.swing.JTextField();
        rButtonCCBuscar = new javax.swing.JRadioButton();
        rButtonNitBuscar = new javax.swing.JRadioButton();
        rButtonOtroBuscar = new javax.swing.JRadioButton();
        btnActualizar = new javax.swing.JButton();
        labelTituloBuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        panelRegistros = new javax.swing.JPanel();
        labelTipoPersonaRegistros = new javax.swing.JLabel();
        cBoxTipoPersonaRegistros = new javax.swing.JComboBox<>();
        labelTituloRegistros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistros = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jSplitPane1.setDividerSize(0);

        panelLateral.setBackground(new java.awt.Color(204, 204, 204));
        panelLateral.setPreferredSize(new java.awt.Dimension(100, 442));

        labelCrear.setBackground(new java.awt.Color(0, 0, 0));
        labelCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/anadir-tercero-24px.png"))); // NOI18N
        labelCrear.setText("Crear");
        labelCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCrear.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelCrear.setPreferredSize(new java.awt.Dimension(150, 42));
        labelCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCrearMouseClicked(evt);
            }
        });

        labelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar-terceros-24px.png"))); // NOI18N
        labelBuscar.setText("Buscar");
        labelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBuscar.setPreferredSize(new java.awt.Dimension(150, 42));
        labelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarMouseClicked(evt);
            }
        });

        labelRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/registros-24px.png"))); // NOI18N
        labelRegistros.setText("Registros");
        labelRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRegistros.setPreferredSize(new java.awt.Dimension(150, 42));
        labelRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(labelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(labelRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelLateral);

        panelCards.setBackground(new java.awt.Color(204, 204, 204));
        panelCards.setPreferredSize(new java.awt.Dimension(200, 442));
        panelCards.setLayout(new java.awt.CardLayout());

        panelCrear.setBackground(new java.awt.Color(255, 255, 255));

        labelTipoPersonaCrear.setText("Tipo de Persona:");
        labelTipoPersonaCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        cBoxTipoPersonaCrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Vendedor", "Proveedor" }));
        cBoxTipoPersonaCrear.setPreferredSize(new java.awt.Dimension(150, 22));
        cBoxTipoPersonaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTipoPersonaCrearActionPerformed(evt);
            }
        });

        labelIDCrear.setText("ID:");
        labelIDCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelDireccionCrear.setText("Direccion:");
        labelDireccionCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelCorreoCrear.setText("Correo:");
        labelCorreoCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelDepartamentoCrear.setText("Departamento:");
        labelDepartamentoCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelNoDocumentoCrear.setText("No. Documento:");
        labelNoDocumentoCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldIDCrear.setEditable(false);
        textFieldIDCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldDireccionCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldCorreoCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldDepartamentoCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldNoDocumentoCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        labelNombreCrear.setText("Nombre:");
        labelNombreCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelTelefonoCrear.setText("Telefono:");
        labelTelefonoCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelCiudadCrear.setText("Ciudad:");
        labelCiudadCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelFechaNacimientoCrear.setText("Fecha Nacimiento:");
        labelFechaNacimientoCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelTipoDocumentoCrear.setText("Tipo Documento:");
        labelTipoDocumentoCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldCiudadCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldTelefonoCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldNombreCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        rButtonCCCrear.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rButtonCCCrear);
        rButtonCCCrear.setText("C.C");
        rButtonCCCrear.setPreferredSize(new java.awt.Dimension(50, 22));

        rButtonNitCrear.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rButtonNitCrear);
        rButtonNitCrear.setText("NIT");
        rButtonNitCrear.setPreferredSize(new java.awt.Dimension(50, 22));

        rButtonOtroCrear.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rButtonOtroCrear);
        rButtonOtroCrear.setText("Otro");
        rButtonOtroCrear.setPreferredSize(new java.awt.Dimension(50, 22));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        labelTituloCrear.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloCrear.setText("Crear Terceros");

        dateChooserFechaNacimientoCrear.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelDepartamentoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldDepartamentoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFechaNacimientoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelCorreoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldCorreoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCiudadCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelDireccionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldDireccionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTelefonoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelIDCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIDCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelNoDocumentoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNoDocumentoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTipoDocumentoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(rButtonCCCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(rButtonNitCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(rButtonOtroCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textFieldNombreCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldTelefonoCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldCiudadCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateChooserFechaNacimientoCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelTituloCrear))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addComponent(btnCrear))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelTipoPersonaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxTipoPersonaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelTituloCrear)
                        .addGap(34, 34, 34)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelTipoPersonaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBoxTipoPersonaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelIDCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIDCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDireccionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDireccionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefonoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTelefonoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCorreoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCorreoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCiudadCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCiudadCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelNombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDepartamentoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDepartamentoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaNacimientoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNoDocumentoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNoDocumentoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTipoDocumentoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rButtonCCCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rButtonNitCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rButtonOtroCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addComponent(dateChooserFechaNacimientoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelCards.add(panelCrear, "panelCrear");
        panelCrear.getAccessibleContext().setAccessibleName("panelCrear");

        panelBuscar.setBackground(new java.awt.Color(255, 255, 255));

        labelTipoPersonaBuscar.setText("Tipo de Persona:");
        labelTipoPersonaBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        cBoxTipoPersonaBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Vendedor", "Proveedor" }));
        cBoxTipoPersonaBuscar.setPreferredSize(new java.awt.Dimension(150, 22));
        cBoxTipoPersonaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTipoPersonaBuscarActionPerformed(evt);
            }
        });

        labelIDBuscar.setText("ID:");
        labelIDBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        labelDireccionBuscar.setText("Direccion:");
        labelDireccionBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        labelCorreoBuscar.setText("Correo:");
        labelCorreoBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        labelDepartamentoBuscar.setText("Departamento:");
        labelDepartamentoBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        labelNoDocumentoBuscar.setText("No. Documento:");
        labelNoDocumentoBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldIDBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldDireccionBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldCorreoBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldDepartamentoBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldNoDocumentoBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        labelNombreBuscar.setText("Nombre:");
        labelNombreBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        labelTelefonoBuscar.setText("Telefono:");
        labelTelefonoBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        labelCiudadBuscar.setText("Ciudad:");
        labelCiudadBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        labelFechaBuscar.setText("Fecha Nacimiento:");
        labelFechaBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        labelTipoDocumentoBuscar.setText("Tipo Documento:");
        labelTipoDocumentoBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldFechaBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldCiudadBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldTelefonoBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldNombreBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        rButtonCCBuscar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rButtonCCBuscar);
        rButtonCCBuscar.setText("C.C");
        rButtonCCBuscar.setPreferredSize(new java.awt.Dimension(50, 22));

        rButtonNitBuscar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rButtonNitBuscar);
        rButtonNitBuscar.setText("NIT");
        rButtonNitBuscar.setPreferredSize(new java.awt.Dimension(50, 22));

        rButtonOtroBuscar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rButtonOtroBuscar);
        rButtonOtroBuscar.setText("Otro");
        rButtonOtroBuscar.setPreferredSize(new java.awt.Dimension(50, 22));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        labelTituloBuscar.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloBuscar.setText("Buscar Terceros");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarLayout.createSequentialGroup()
                .addContainerGap(486, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(27, 27, 27))
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(labelCorreoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldCorreoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(labelDepartamentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldDepartamentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(labelDireccionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldDireccionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(labelIDBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIDBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(labelTipoPersonaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cBoxTipoPersonaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(labelNoDocumentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNoDocumentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefonoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCiudadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTipoDocumentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(rButtonCCBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(rButtonNitBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(rButtonOtroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textFieldFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCiudadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTelefonoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelTituloBuscar))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloBuscar)
                .addGap(34, 34, 34)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTipoPersonaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cBoxTipoPersonaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIDBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldIDBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDireccionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefonoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTelefonoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCorreoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCorreoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCiudadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCiudadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDepartamentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDepartamentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoDocumentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNoDocumentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipoDocumentoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rButtonCCBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rButtonNitBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rButtonOtroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(53, 53, 53))
        );

        panelCards.add(panelBuscar, "panelBuscar");
        panelBuscar.getAccessibleContext().setAccessibleName("panelBuscar");

        panelRegistros.setBackground(new java.awt.Color(255, 255, 255));

        labelTipoPersonaRegistros.setText("Tipo de Persona:");
        labelTipoPersonaRegistros.setPreferredSize(new java.awt.Dimension(110, 16));

        cBoxTipoPersonaRegistros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Vendedor", "Proveedor" }));
        cBoxTipoPersonaRegistros.setSelectedIndex(cBoxTipoPersonaRegistros.getSelectedIndex());
        cBoxTipoPersonaRegistros.setPreferredSize(new java.awt.Dimension(150, 22));
        cBoxTipoPersonaRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTipoPersonaRegistrosActionPerformed(evt);
            }
        });

        labelTituloRegistros.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloRegistros.setText("RegistrosTerceros");

        tableRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Direccion", "Telefono", "Correo", "Ciudad", "Departamento", "Tipo de Documento", "No. Documento"
            }
        ));
        tableRegistros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableRegistros.setEnabled(false);
        jScrollPane1.setViewportView(tableRegistros);

        javax.swing.GroupLayout panelRegistrosLayout = new javax.swing.GroupLayout(panelRegistros);
        panelRegistros.setLayout(panelRegistrosLayout);
        panelRegistrosLayout.setHorizontalGroup(
            panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloRegistros)
                    .addComponent(labelTipoPersonaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegistrosLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(cBoxTipoPersonaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelRegistrosLayout.setVerticalGroup(
            panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloRegistros)
                .addGap(27, 27, 27)
                .addGroup(panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTipoPersonaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxTipoPersonaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelCards.add(panelRegistros, "panelRegistros");

        jSplitPane1.setRightComponent(panelCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCrearMouseClicked
        cardLayout.show(panelCards, "panelCrear");
    }//GEN-LAST:event_labelCrearMouseClicked

    private void labelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseClicked
        cardLayout.show(panelCards, "panelBuscar");
    }//GEN-LAST:event_labelBuscarMouseClicked

    private void labelRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrosMouseClicked
        cardLayout.show(panelCards, "panelRegistros");
        cBoxTipoPersonaRegistros.setSelectedIndex(cBoxTipoPersonaRegistros.getSelectedIndex());
        String persona = cBoxTipoPersonaRegistros.getSelectedItem().toString();
        switch (persona) {
            case "Cliente" -> {
                refrescarTabla(1);
            }
            case "Vendedor" -> {
                refrescarTabla(2);
            }
            case "Proveedor" -> {
                refrescarTabla(3);
            }
        }

    }//GEN-LAST:event_labelRegistrosMouseClicked

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String persona = cBoxTipoPersonaCrear.getSelectedItem().toString();
        String nombre = textFieldNombreCrear.getText();
        String direccion = textFieldDireccionCrear.getText();
        String telefono = textFieldTelefonoCrear.getText();
        String correo = textFieldCorreoCrear.getText();
        String ciudad = textFieldCiudadCrear.getText();
        String departamento = textFieldDepartamentoCrear.getText();
        String nroDocumento = textFieldNoDocumentoCrear.getText();
        //String fechaNacimiento = textFieldFechaCrear.getText();

        String id = "0";
        String tipoDocumento = "";

        if (rButtonCCCrear.isSelected()) {
            tipoDocumento = "C.C";
        } else if (rButtonNitCrear.isSelected()) {
            tipoDocumento = "NIT";
        } else if (rButtonOtroCrear.isSelected()) {
            tipoDocumento = "Otro";
        }
        switch (persona) {
            case "Cliente" -> {
                boolean clienteCreado = false;
                try {
                    fecha = dateChooserFechaNacimientoCrear.getDate();
                    String fechaNacimiento = DateFormat.getDateInstance().format(fecha);
                    clienteCreado = controlCliente.crear(nombre, direccion, telefono, correo,
                            ciudad, departamento, tipoDocumento, Integer.parseInt(nroDocumento), fechaNacimiento,
                            Integer.parseInt(id));
                    limpiarCampos(1);
                    textFieldIDCrear.setText(controlCliente.obtenerId(persona, persona + "s".toLowerCase()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
                }

                if (clienteCreado) {
                    JOptionPane.showMessageDialog(this, "El cliente ha sido creado exitosamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un problema durante la creacion del cliente.");
                }
            }
            case "Vendedor" -> {
                boolean vendedorCreado = false;
                try {
                    vendedorCreado = controlVendedor.crear(nombre, direccion, telefono, correo, ciudad, departamento,
                            tipoDocumento, Integer.parseInt(nroDocumento), Integer.parseInt(id));
                    limpiarCampos(1);
                    textFieldIDCrear.setText(controlCliente.obtenerId(persona, persona + "es".toLowerCase()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
                }

                if (vendedorCreado) {
                    JOptionPane.showMessageDialog(this, "El vendedor ha sido creado exitosamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un problema durante la creacion del vendedor.");
                }
            }
            case "Proveedor" -> {
                boolean proveedorCreado = false;
                try {
                    proveedorCreado = controlProveedor.crear(nombre, direccion, telefono, correo,
                            ciudad, departamento, tipoDocumento, Integer.parseInt(nroDocumento),
                            Integer.parseInt(id));
                    limpiarCampos(1);
                    textFieldIDCrear.setText(controlCliente.obtenerId(persona, persona + "es".toLowerCase()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
                }

                if (proveedorCreado) {
                    JOptionPane.showMessageDialog(this, "El proveedor ha sido creado exitosamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un problema durante la creacion del proveedor.");
                }
            }
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cBoxTipoPersonaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTipoPersonaCrearActionPerformed
        String persona = cBoxTipoPersonaCrear.getSelectedItem().toString();
        switch (persona) {
            case "Cliente" -> {
                dateChooserFechaNacimientoCrear.setEnabled(true);
                //textFieldFechaCrear.setEditable(true);
                textFieldIDCrear.setText(controlCliente.obtenerId(persona, persona + "s".toLowerCase()));
            }
            case "Vendedor" -> {
                dateChooserFechaNacimientoCrear.setEnabled(false);
                //textFieldFechaCrear.setEditable(false);
                textFieldIDCrear.setText(controlCliente.obtenerId(persona, persona + "es".toLowerCase()));
            }
            case "Proveedor" -> {
                //textFieldFechaCrear.setEditable(false);
                dateChooserFechaNacimientoCrear.setEnabled(false);
                textFieldIDCrear.setText(controlCliente.obtenerId(persona, persona + "es".toLowerCase()));
            }
        }
    }//GEN-LAST:event_cBoxTipoPersonaCrearActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            String persona = cBoxTipoPersonaBuscar.getSelectedItem().toString();
            String nombre = textFieldNombreBuscar.getText();
            String direccion = textFieldDireccionBuscar.getText();
            String telefono = textFieldTelefonoBuscar.getText();
            String correo = textFieldCorreoBuscar.getText();
            String ciudad = textFieldCiudadBuscar.getText();
            String departamento = textFieldDepartamentoBuscar.getText();
            String nroDocumento = textFieldNoDocumentoBuscar.getText();
            String fechaNacimiento = textFieldFechaBuscar.getText();
            int id = Integer.parseInt(textFieldIDBuscar.getText());
            String tipoDocumento = "";

            if (rButtonCCBuscar.isSelected()) {
                tipoDocumento = "C.C";
            } else if (rButtonNitBuscar.isSelected()) {
                tipoDocumento = "NIT";
            } else if (rButtonOtroBuscar.isSelected()) {
                tipoDocumento = "Otro";
            }
            switch (persona) {
                case "Cliente" -> {
                    boolean clienteActualizado = false;
                    try {
                        clienteActualizado = controlCliente.actualizar(nombre, direccion, telefono, correo,
                                ciudad, departamento, tipoDocumento, Integer.parseInt(nroDocumento), fechaNacimiento,
                                id);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Cliente no existe.");
                    }

                    if (clienteActualizado) {
                        JOptionPane.showMessageDialog(this, "El cliente ha sido actualizado exitosamente.");
                    }
                    limpiarCampos(2);
                }
                case "Vendedor" -> {
                    boolean vendedorActualizado = false;
                    try {
                        vendedorActualizado = controlVendedor.actualizar(nombre, direccion, telefono, correo, ciudad, departamento,
                                tipoDocumento, Integer.parseInt(nroDocumento), id);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Vendedor no existe.");
                    }

                    if (vendedorActualizado) {
                        JOptionPane.showMessageDialog(this, "El vendedor ha sido actualizado exitosamente.");
                    }
                    limpiarCampos(2);
                }
                case "Proveedor" -> {
                    boolean proveedorActualizado = false;
                    try {
                        proveedorActualizado = controlProveedor.actualizar(nombre, direccion, telefono,
                                correo, ciudad, departamento, tipoDocumento, Integer.parseInt(nroDocumento), id);

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "El proveedor no existe.");
                    }

                    if (proveedorActualizado) {
                        JOptionPane.showMessageDialog(this, "El proveedor ha sido actualizado exitosamente.");
                    }
                    limpiarCampos(2);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int id = Integer.parseInt(textFieldIDBuscar.getText());
            String persona = cBoxTipoPersonaBuscar.getSelectedItem().toString();

            var matrizDevuelta = switch (persona) {
                case "Cliente" ->
                    controlCliente.buscar(id);

                case "Vendedor" ->
                    controlVendedor.buscar(id);

                case "Proveedor" ->
                    controlProveedor.buscar(id);
                default ->
                    null;
            };
            if (matrizDevuelta.length > 9) {
                textFieldFechaBuscar.setText(matrizDevuelta[9]);
            }
            if (matrizDevuelta != null) {
                textFieldIDBuscar.setText(matrizDevuelta[0]);
                textFieldNombreBuscar.setText(matrizDevuelta[1]);
                textFieldDireccionBuscar.setText(matrizDevuelta[2]);
                textFieldTelefonoBuscar.setText(matrizDevuelta[3]);
                textFieldCorreoBuscar.setText(matrizDevuelta[4]);
                textFieldCiudadBuscar.setText(matrizDevuelta[5]);
                textFieldDepartamentoBuscar.setText(matrizDevuelta[6]);
                textFieldNoDocumentoBuscar.setText(matrizDevuelta[8]);
                String tipo = matrizDevuelta[7];
                switch (tipo) {
                    case "C.C" ->
                        rButtonCCBuscar.setSelected(true);
                    case "NIT" ->
                        rButtonNitBuscar.setSelected(true);
                    case "Otro" ->
                        rButtonOtroBuscar.setSelected(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se ha encontrado informacion.");
                limpiarCampos(2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se ha podido realizar la busqueda, intente nuevamente.");
            limpiarCampos(2);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cBoxTipoPersonaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTipoPersonaBuscarActionPerformed
        String persona = cBoxTipoPersonaBuscar.getSelectedItem().toString();
        switch (persona) {
            case "Cliente" -> {
                textFieldFechaBuscar.setEditable(true);
            }
            case "Vendedor" -> {
                textFieldFechaBuscar.setEditable(false);
            }
            case "Proveedor" -> {
                textFieldFechaBuscar.setEditable(false);
            }
        }
        limpiarCampos(2);
    }//GEN-LAST:event_cBoxTipoPersonaBuscarActionPerformed

    private void cBoxTipoPersonaRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTipoPersonaRegistrosActionPerformed
        String persona = cBoxTipoPersonaRegistros.getSelectedItem().toString();
        switch (persona) {
            case "Cliente" -> {
                refrescarTabla(1);
            }
            case "Vendedor" -> {
                refrescarTabla(2);
            }
            case "Proveedor" -> {
                refrescarTabla(3);
            }
        }
    }//GEN-LAST:event_cBoxTipoPersonaRegistrosActionPerformed

    private void limpiarCampos(int opcion) {

        switch (opcion) {
            case 1 -> {
                textFieldNombreCrear.setText("");
                textFieldDireccionCrear.setText("");
                textFieldTelefonoCrear.setText("");
                textFieldCorreoCrear.setText("");
                textFieldCiudadCrear.setText("");
                textFieldDepartamentoCrear.setText("");
                textFieldNoDocumentoCrear.setText("");
                dateChooserFechaNacimientoCrear.setCalendar(null);
                //textFieldFechaCrear.setText("");
            }
            case 2 -> {
                textFieldNombreBuscar.setText("");
                textFieldDireccionBuscar.setText("");
                textFieldTelefonoBuscar.setText("");
                textFieldCorreoBuscar.setText("");
                textFieldCiudadBuscar.setText("");
                textFieldDepartamentoBuscar.setText("");
                textFieldNoDocumentoBuscar.setText("");
                textFieldFechaBuscar.setText("");
            }
        }

    }

    public void refrescarTabla(int opcion) {

        switch (opcion) {
            case 1 -> {
                //Se establecen los elementos de la cabecera de la tabla
                String[] cabeceraCliente = {"Id", "Nombre", "Direccion", "Telefono", "Correo", "Ciudad", "Departamento",
                    "Tipo Documento", "No. Documento", "Fecha de Nacimiento"};
                //Se recogen los datos de los clientes añadidos en el almacenamiento temporal
                String[][] matrizClientes = controlCliente.refrescarTablaCliente();
                //Se agregan los datos y la cabecera de la tabla al modelo
                modeloTablaPersona.setDataVector(matrizClientes, cabeceraCliente);
                //Se agrega el modelo a la vista
                tableRegistros.setModel(modeloTablaPersona);
            }
            case 2 -> {
                String[] cabeceraVendedor = {"Id", "Nombre", "Direccion", "Telefono", "Correo", "Ciudad", "Departamento",
                    "Tipo Documento", "No. Documento"};
                String[][] matrizVendedores = controlVendedor.refrescarTablaVendedor();
                modeloTablaPersona.setDataVector(matrizVendedores, cabeceraVendedor);
                tableRegistros.setModel(modeloTablaPersona);
            }
            case 3 -> {
                String[] cabeceraProveedor = {"Id", "Nombre", "Direccion", "Telefono", "Correo", "Ciudad", "Departamento",
                    "Tipo Documento", "No. Documento"};
                String[][] matrizProveedores = controlProveedor.refrescarTablaProveedor();
                modeloTablaPersona.setDataVector(matrizProveedores, cabeceraProveedor);
                tableRegistros.setModel(modeloTablaPersona);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cBoxTipoPersonaBuscar;
    private javax.swing.JComboBox<String> cBoxTipoPersonaCrear;
    private javax.swing.JComboBox<String> cBoxTipoPersonaRegistros;
    private com.toedter.calendar.JDateChooser dateChooserFechaNacimientoCrear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelCiudadBuscar;
    private javax.swing.JLabel labelCiudadCrear;
    private javax.swing.JLabel labelCorreoBuscar;
    private javax.swing.JLabel labelCorreoCrear;
    private javax.swing.JLabel labelCrear;
    private javax.swing.JLabel labelDepartamentoBuscar;
    private javax.swing.JLabel labelDepartamentoCrear;
    private javax.swing.JLabel labelDireccionBuscar;
    private javax.swing.JLabel labelDireccionCrear;
    private javax.swing.JLabel labelFechaBuscar;
    private javax.swing.JLabel labelFechaNacimientoCrear;
    private javax.swing.JLabel labelIDBuscar;
    private javax.swing.JLabel labelIDCrear;
    private javax.swing.JLabel labelNoDocumentoBuscar;
    private javax.swing.JLabel labelNoDocumentoCrear;
    private javax.swing.JLabel labelNombreBuscar;
    private javax.swing.JLabel labelNombreCrear;
    private javax.swing.JLabel labelRegistros;
    private javax.swing.JLabel labelTelefonoBuscar;
    private javax.swing.JLabel labelTelefonoCrear;
    private javax.swing.JLabel labelTipoDocumentoBuscar;
    private javax.swing.JLabel labelTipoDocumentoCrear;
    private javax.swing.JLabel labelTipoPersonaBuscar;
    private javax.swing.JLabel labelTipoPersonaCrear;
    private javax.swing.JLabel labelTipoPersonaRegistros;
    private javax.swing.JLabel labelTituloBuscar;
    private javax.swing.JLabel labelTituloCrear;
    private javax.swing.JLabel labelTituloRegistros;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelRegistros;
    private javax.swing.JRadioButton rButtonCCBuscar;
    private javax.swing.JRadioButton rButtonCCCrear;
    private javax.swing.JRadioButton rButtonNitBuscar;
    private javax.swing.JRadioButton rButtonNitCrear;
    private javax.swing.JRadioButton rButtonOtroBuscar;
    private javax.swing.JRadioButton rButtonOtroCrear;
    private javax.swing.JTable tableRegistros;
    private javax.swing.JTextField textFieldCiudadBuscar;
    private javax.swing.JTextField textFieldCiudadCrear;
    private javax.swing.JTextField textFieldCorreoBuscar;
    private javax.swing.JTextField textFieldCorreoCrear;
    private javax.swing.JTextField textFieldDepartamentoBuscar;
    private javax.swing.JTextField textFieldDepartamentoCrear;
    private javax.swing.JTextField textFieldDireccionBuscar;
    private javax.swing.JTextField textFieldDireccionCrear;
    private javax.swing.JTextField textFieldFechaBuscar;
    private javax.swing.JTextField textFieldIDBuscar;
    private javax.swing.JTextField textFieldIDCrear;
    private javax.swing.JTextField textFieldNoDocumentoBuscar;
    private javax.swing.JTextField textFieldNoDocumentoCrear;
    private javax.swing.JTextField textFieldNombreBuscar;
    private javax.swing.JTextField textFieldNombreCrear;
    private javax.swing.JTextField textFieldTelefonoBuscar;
    private javax.swing.JTextField textFieldTelefonoCrear;
    // End of variables declaration//GEN-END:variables

}
