/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.EstadoPedido;
import Classes.Producto;
import Controller.*;
import java.awt.AWTException;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicLabelUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Leonardo Perdomo
 */
public class FrmViewPedidos2 extends javax.swing.JInternalFrame {

    private final CardLayout cardLayout;
    private final ControllerPedidos controlPedidos;
    private final ControllerInventario controlInventario;
    private DefaultTableModel modeloTablaPedido;
    private ArrayList<Producto> tablaPro;

    /**
     * Creates new form FrmViewPedidos2
     */
    public FrmViewPedidos2() {

        controlPedidos = new ControllerPedidos();
        controlInventario = new ControllerInventario();
        modeloTablaPedido = new DefaultTableModel();
        tablaPro = new ArrayList<Producto>();

        initComponents();

        Component[] components = this.getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JLabel) {
                ((JLabel) component).setUI(new BasicLabelUI());
                ((JLabel) component).setFocusCycleRoot(false);
            }

        }
        cardLayout = (CardLayout) (panelCards.getLayout());
        textFieldIdPedidoCrear.setText(controlPedidos.obtenerId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelLateral = new javax.swing.JPanel();
        labelCrear = new javax.swing.JLabel();
        labelBuscar = new javax.swing.JLabel();
        panelCards = new javax.swing.JPanel();
        panelCrear = new javax.swing.JPanel();
        labelIdPedidoCrear = new javax.swing.JLabel();
        labelIdClienteCrear = new javax.swing.JLabel();
        labelIdVendedorCrear = new javax.swing.JLabel();
        textFieldIdClienteCrear = new javax.swing.JTextField();
        textFieldIdVendedorCrear = new javax.swing.JTextField();
        labelEstadoPedidoCrear = new javax.swing.JLabel();
        labelNombreClienteCrear = new javax.swing.JLabel();
        textFieldNombreClienteCrear = new javax.swing.JTextField();
        btnCrearPedido = new javax.swing.JButton();
        labelTituloCrear = new javax.swing.JLabel();
        textFieldIdPedidoCrear = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePedidosCrear = new javax.swing.JTable();
        cBEstadoPedidoCrear = new javax.swing.JComboBox<>();
        panelBuscar = new javax.swing.JPanel();
        labelTituloBuscar = new javax.swing.JLabel();
        btnActualizarPedido = new javax.swing.JButton();
        cBEstadoPedidoBuscar = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePedidosBuscar = new javax.swing.JTable();
        labelIdClienteBuscar = new javax.swing.JLabel();
        textFieldNombreClienteBuscar = new javax.swing.JTextField();
        textFieldIdVendedorBuscar = new javax.swing.JTextField();
        labelEstadoPedidoBuscar = new javax.swing.JLabel();
        labelIdVendedorBuscar = new javax.swing.JLabel();
        textFieldIdPedidoBuscar = new javax.swing.JTextField();
        textFieldIdClienteBuscar = new javax.swing.JTextField();
        labelIdPedidoBuscar = new javax.swing.JLabel();
        labelNombreClienteBuscar = new javax.swing.JLabel();
        btnBuscarPedido = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(740, 600));

        jSplitPane1.setDividerSize(0);

        panelLateral.setBackground(new java.awt.Color(204, 204, 204));
        panelLateral.setPreferredSize(new java.awt.Dimension(100, 442));

        labelCrear.setBackground(new java.awt.Color(0, 0, 0));
        labelCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/añadir-pedido-24px.png"))); // NOI18N
        labelCrear.setText("Crear");
        labelCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCrear.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelCrear.setPreferredSize(new java.awt.Dimension(150, 42));
        labelCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCrearMouseClicked(evt);
            }
        });

        labelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar-pedido-24px.png"))); // NOI18N
        labelBuscar.setText("Buscar");
        labelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBuscar.setPreferredSize(new java.awt.Dimension(150, 42));
        labelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(labelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelLateral);

        panelCards.setBackground(new java.awt.Color(204, 204, 204));
        panelCards.setPreferredSize(new java.awt.Dimension(200, 442));
        panelCards.setLayout(new java.awt.CardLayout());

        panelCrear.setBackground(new java.awt.Color(255, 255, 255));

        labelIdPedidoCrear.setText("ID Pedido:");
        labelIdPedidoCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelIdClienteCrear.setText("Cod Cliente:");
        labelIdClienteCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelIdVendedorCrear.setText("Cod Vendedor:");
        labelIdVendedorCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldIdClienteCrear.setPreferredSize(new java.awt.Dimension(150, 22));
        textFieldIdClienteCrear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldIdClienteCrearFocusLost(evt);
            }
        });

        textFieldIdVendedorCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        labelEstadoPedidoCrear.setText("Estado del Pedido:");
        labelEstadoPedidoCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelNombreClienteCrear.setText("Nombre Cliente:");
        labelNombreClienteCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldNombreClienteCrear.setEditable(false);
        textFieldNombreClienteCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        btnCrearPedido.setText("Crear");
        btnCrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPedidoActionPerformed(evt);
            }
        });

        labelTituloCrear.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloCrear.setText("Crear Pedidos");

        textFieldIdPedidoCrear.setEditable(false);

        tablePedidosCrear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre", "Unidad", "Cantidad", "Precio de Venta", "Total Parcial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePedidosCrear.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablePedidosCrear.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePedidosCrear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablePedidosCrearKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablePedidosCrear);
        if (tablePedidosCrear.getColumnModel().getColumnCount() > 0) {
            tablePedidosCrear.getColumnModel().getColumn(0).setResizable(false);
            tablePedidosCrear.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablePedidosCrear.getColumnModel().getColumn(1).setResizable(false);
            tablePedidosCrear.getColumnModel().getColumn(1).setPreferredWidth(190);
        }

        cBEstadoPedidoCrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "CONFIRMADO", "CANCELADO", "PAGADO", "ENTREGADO" }));
        cBEstadoPedidoCrear.setToolTipText("");

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addComponent(btnCrearPedido))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelTituloCrear))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelIdPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIdPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEstadoPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cBEstadoPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelIdClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIdClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNombreClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldNombreClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelIdVendedorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIdVendedorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelTituloCrear)
                        .addGap(31, 31, 31)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(textFieldIdPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEstadoPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBEstadoPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelIdClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIdClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIdVendedorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIdVendedorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNombreClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearPedido)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        panelCards.add(panelCrear, "panelCrear");

        panelBuscar.setBackground(new java.awt.Color(255, 255, 255));

        labelTituloBuscar.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloBuscar.setText("Buscar Pedido");

        btnActualizarPedido.setText("Actualizar");
        btnActualizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPedidoActionPerformed(evt);
            }
        });

        cBEstadoPedidoBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "CONFIRMADO", "CANCELADO", "PAGADO", "ENTREGADO" }));

        tablePedidosBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre", "Unidad", "Cantidad", "Precio de Venta", "Total Parcial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePedidosBuscar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablePedidosBuscar.setEnabled(false);
        tablePedidosBuscar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tablePedidosBuscar);
        if (tablePedidosBuscar.getColumnModel().getColumnCount() > 0) {
            tablePedidosBuscar.getColumnModel().getColumn(0).setResizable(false);
            tablePedidosBuscar.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablePedidosBuscar.getColumnModel().getColumn(1).setResizable(false);
            tablePedidosBuscar.getColumnModel().getColumn(1).setPreferredWidth(190);
        }

        labelIdClienteBuscar.setText("Cod Cliente:");
        labelIdClienteBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldNombreClienteBuscar.setEditable(false);
        textFieldNombreClienteBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldIdVendedorBuscar.setEditable(false);
        textFieldIdVendedorBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        labelEstadoPedidoBuscar.setText("Estado del Pedido:");
        labelEstadoPedidoBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        labelIdVendedorBuscar.setText("Cod Vendedor:");
        labelIdVendedorBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldIdClienteBuscar.setEditable(false);
        textFieldIdClienteBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        labelIdPedidoBuscar.setText("ID Pedido:");
        labelIdPedidoBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        labelNombreClienteBuscar.setText("Nombre Cliente:");
        labelNombreClienteBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        btnBuscarPedido.setText("Buscar Pedido");
        btnBuscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActualizarPedido)
                    .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBuscarLayout.createSequentialGroup()
                            .addComponent(labelIdPedidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldIdPedidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelEstadoPedidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cBEstadoPedidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelTituloBuscar)
                        .addGroup(panelBuscarLayout.createSequentialGroup()
                            .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBuscarLayout.createSequentialGroup()
                                    .addComponent(labelIdVendedorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldIdVendedorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBuscarLayout.createSequentialGroup()
                                    .addComponent(labelIdClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldIdClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(labelNombreClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(textFieldNombreClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloBuscar)
                .addGap(31, 31, 31)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(textFieldIdPedidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdPedidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEstadoPedidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBEstadoPedidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelIdClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIdClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIdVendedorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIdVendedorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNombreClienteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarPedido)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        panelCards.add(panelBuscar, "panelBuscar");

        jSplitPane1.setRightComponent(panelCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCrearMouseClicked
        cardLayout.show(panelCards, "panelCrear");
    }//GEN-LAST:event_labelCrearMouseClicked

    private void labelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseClicked
        cardLayout.show(panelCards, "panelBuscar");
    }//GEN-LAST:event_labelBuscarMouseClicked


    private void tablePedidosCrearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablePedidosCrearKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (tablePedidosCrear.isEditing()) {
                    tablePedidosCrear.getCellEditor().stopCellEditing();
                }

                int columna = tablePedidosCrear.getSelectedColumn();
                int filaSeleccionada = tablePedidosCrear.getSelectedRow();

                //Pregunta si el cursor se encuentra en la columna de ID para agregar los productos
                if (columna == 0) {
                    String codigo = tablePedidosCrear.getValueAt(filaSeleccionada, 0).toString();

                    try {
                        String[][] productoDevuelto = controlInventario.buscar(Integer.parseInt(codigo));
                        String[] contenido = controlPedidos.organizarProductos(productoDevuelto);

                        for (int i = 0; i < contenido.length; i++) {
                            tablePedidosCrear.setValueAt(contenido[i], filaSeleccionada, i);
                        }

                    } catch (NumberFormatException e) {
                        e.getMessage();
                    }
                    refrescarTabla(1);
                    if (evt.getKeyCode() == KeyEvent.VK_TAB) {
                        tablePedidosCrear.changeSelection(filaSeleccionada, 2, false, false);
                    } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        tablePedidosCrear.changeSelection(filaSeleccionada - 2, 3, true, true);
                    }

                    //Toolkit.getDefaultToolkit().beep();
                    //System.out.println("TAB Presionado");
                } else if (columna == 4) {
                    String cantidad = tablePedidosCrear.getValueAt(filaSeleccionada, 3).toString();
                    String precio = tablePedidosCrear.getValueAt(filaSeleccionada, 4).toString();
                    int total = Integer.parseInt(cantidad) * Integer.parseInt(precio);
                    tablePedidosCrear.setValueAt(Integer.toString(total), filaSeleccionada, 5);

                    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        tablePedidosCrear.changeSelection(filaSeleccionada, 3, true, true);
                        filaSeleccionada = tablePedidosCrear.getSelectedRow();
                        tablePedidosCrear.changeSelection(filaSeleccionada, 0, true, true);
                    } else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
                        filaSeleccionada += 1;
                        tablePedidosCrear.changeSelection(filaSeleccionada, 0, true, true);
                    }
                    refrescarTabla(2);
                }
            }

        } catch (NumberFormatException e) {
            e.getMessage();
        }

    }//GEN-LAST:event_tablePedidosCrearKeyPressed

    private void textFieldIdClienteCrearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldIdClienteCrearFocusLost
        if (!(textFieldIdClienteCrear.getText().equals(""))) {
            String idCliente = textFieldIdClienteCrear.getText();
            String nombreCliente = controlPedidos.buscarCliente(Integer.parseInt(idCliente));
            textFieldNombreClienteCrear.setText(nombreCliente);
        }
    }//GEN-LAST:event_textFieldIdClienteCrearFocusLost

    private void btnCrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPedidoActionPerformed

        try {
            int fila = tablePedidosCrear.getRowCount();
            int columna = tablePedidosCrear.getColumnCount();
            fila -= 1;
            String[][] array_tabla = new String[fila][columna];

            for (int i = 0; i < fila; i++) {
                for (int j = 0; j < columna; j++) {
                    array_tabla[i][j] = (String) tablePedidosCrear.getValueAt(i, j);
                }

            }
            int idPedido = Integer.parseInt(textFieldIdPedidoCrear.getText());
            int idCliente = Integer.parseInt(textFieldIdClienteCrear.getText());
            int idVendedor = Integer.parseInt(textFieldIdVendedorCrear.getText());
            String estadoPedido = cBEstadoPedidoCrear.getSelectedItem().toString();

            try {
                controlPedidos.crearPedido(array_tabla, idPedido, idCliente, idVendedor, estadoPedido);
                JOptionPane.showConfirmDialog(this, "Se ha creado satisfactoriamente el pedido.");
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

            limpiarCampos();

            System.out.println("Bien");
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Por favor rellene los campos faltantes.");
        }
    }//GEN-LAST:event_btnCrearPedidoActionPerformed

    private void btnActualizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPedidoActionPerformed
        // TODO add your handling code here:
        try {
            if (textFieldIdPedidoBuscar.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Primero realice la busqueda del pedido.");
            } else {
                String estadoPedido = cBEstadoPedidoBuscar.getSelectedItem().toString();
                String idPedido = textFieldIdPedidoBuscar.getText();
                controlPedidos.actualizarEstado(estadoPedido, idPedido);
                JOptionPane.showMessageDialog(this, "El estado del pedido ha sido actualizado.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Primero realice la busqueda del pedido.");
        }

    }//GEN-LAST:event_btnActualizarPedidoActionPerformed

    private void btnBuscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPedidoActionPerformed
        // TODO comentar codigo
        reinicializarTablaBuscar();
        try {
            int idPedido = Integer.parseInt(textFieldIdPedidoBuscar.getText());
            String[][] tabla = controlPedidos.buscarPedido(idPedido);
            int columnas = tabla[0].length;
            textFieldIdClienteBuscar.setText(tabla[0][columnas - 3]);
            String nombreCliente = controlPedidos.buscarCliente(Integer.parseInt(tabla[0][columnas - 3]));
            textFieldNombreClienteBuscar.setText(nombreCliente);
            textFieldIdVendedorBuscar.setText(tabla[0][columnas - 2]);
            cBEstadoPedidoBuscar.setSelectedItem(tabla[0][columnas - 1]);
            int filas = tabla.length;

            for (int i = 0; i < filas; i++) {

                for (int j = 0; j < columnas - 3; j++) {
                    tablePedidosBuscar.setValueAt(tabla[i][j], i, j);

                }
                refrescarTabla(3);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Introduzca el ID del pedido a buscar.");
        }
    }//GEN-LAST:event_btnBuscarPedidoActionPerformed

    /**
     * Metodo que se encarga de reiniciar los componentes de la vista una vez se
     * ha creado el pedido. Para reinicializar la tabla, es necesario copiar el
     * codigo generado por el jFormDesigner
     */
    public void limpiarCampos() {
        textFieldIdPedidoCrear.setText(controlPedidos.obtenerId());
        textFieldIdClienteCrear.setText("");
        textFieldIdVendedorCrear.setText("");
        textFieldNombreClienteCrear.setText("");
        tablePedidosCrear.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null}
                },
                new String[]{
                    "ID Producto", "Nombre", "Unidad", "Cantidad", "Precio de Venta", "Total Parcial"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tablePedidosCrear.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablePedidosCrear.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePedidosCrear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablePedidosCrearKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablePedidosCrear);
        if (tablePedidosCrear.getColumnModel().getColumnCount() > 0) {
            tablePedidosCrear.getColumnModel().getColumn(0).setResizable(false);
            tablePedidosCrear.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablePedidosCrear.getColumnModel().getColumn(1).setResizable(false);
            tablePedidosCrear.getColumnModel().getColumn(1).setPreferredWidth(190);
        }
    }

    public void reinicializarTablaBuscar() {
        tablePedidosBuscar.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null}
                },
                new String[]{
                    "ID Producto", "Nombre", "Unidad", "Cantidad", "Precio de Venta", "Total Parcial"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tablePedidosBuscar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablePedidosBuscar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePedidosBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablePedidosCrearKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tablePedidosBuscar);
        if (tablePedidosBuscar.getColumnModel().getColumnCount() > 0) {
            tablePedidosBuscar.getColumnModel().getColumn(0).setResizable(false);
            tablePedidosBuscar.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablePedidosBuscar.getColumnModel().getColumn(1).setResizable(false);
            tablePedidosBuscar.getColumnModel().getColumn(1).setPreferredWidth(190);
        }
    }

    public void refrescarTabla(int opcion) {

        switch (opcion) {
            case 1 -> {
                modeloTablaPedido = (DefaultTableModel) tablePedidosCrear.getModel();
                modeloTablaPedido.addRow(new String[]{"", ""});
                tablePedidosCrear.setModel(modeloTablaPedido);
            }
            case 2 -> {
                modeloTablaPedido = (DefaultTableModel) tablePedidosCrear.getModel();
                tablePedidosCrear.setModel(modeloTablaPedido);
            }
            case 3 -> {
                modeloTablaPedido = (DefaultTableModel) tablePedidosBuscar.getModel();
                modeloTablaPedido.addRow(new String[]{"", ""});
                tablePedidosBuscar.setModel(modeloTablaPedido);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPedido;
    private javax.swing.JButton btnBuscarPedido;
    private javax.swing.JButton btnCrearPedido;
    private javax.swing.JComboBox<String> cBEstadoPedidoBuscar;
    private javax.swing.JComboBox<String> cBEstadoPedidoCrear;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelCrear;
    private javax.swing.JLabel labelEstadoPedidoBuscar;
    private javax.swing.JLabel labelEstadoPedidoCrear;
    private javax.swing.JLabel labelIdClienteBuscar;
    private javax.swing.JLabel labelIdClienteCrear;
    private javax.swing.JLabel labelIdPedidoBuscar;
    private javax.swing.JLabel labelIdPedidoCrear;
    private javax.swing.JLabel labelIdVendedorBuscar;
    private javax.swing.JLabel labelIdVendedorCrear;
    private javax.swing.JLabel labelNombreClienteBuscar;
    private javax.swing.JLabel labelNombreClienteCrear;
    private javax.swing.JLabel labelTituloBuscar;
    private javax.swing.JLabel labelTituloCrear;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JTable tablePedidosBuscar;
    private javax.swing.JTable tablePedidosCrear;
    private javax.swing.JTextField textFieldIdClienteBuscar;
    private javax.swing.JTextField textFieldIdClienteCrear;
    private javax.swing.JTextField textFieldIdPedidoBuscar;
    private javax.swing.JTextField textFieldIdPedidoCrear;
    private javax.swing.JTextField textFieldIdVendedorBuscar;
    private javax.swing.JTextField textFieldIdVendedorCrear;
    private javax.swing.JTextField textFieldNombreClienteBuscar;
    private javax.swing.JTextField textFieldNombreClienteCrear;
    // End of variables declaration//GEN-END:variables
}
