/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerInventario;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo Perdomo
 */
public class FrmViewProductos extends javax.swing.JInternalFrame {

    private final ControllerInventario controlInventario;

    /**
     * Creates new form FrmViewProductos
     */
    public FrmViewProductos() {
        controlInventario = new ControllerInventario();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        labelIdProducto = new javax.swing.JLabel();
        labelIdProveedor = new javax.swing.JLabel();
        textFieldIdProveedor = new javax.swing.JTextField();
        textFieldCantidad = new javax.swing.JTextField();
        textFieldNombre = new javax.swing.JTextField();
        textFieldIdProducto = new javax.swing.JTextField();
        textFieldPrecio = new javax.swing.JTextField();
        agregarBtn = new javax.swing.JButton();
        buscarBtn = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescripcion = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestor de Productos");

        labelNombre.setText("Nombre: ");

        labelPrecio.setText("Precio:");

        labelCantidad.setText("Cantidad:");

        labelIdProducto.setText("Id:");

        labelIdProveedor.setText("Id Proveedor:");

        agregarBtn.setText("Agregar");
        agregarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        actualizarBtn.setText("Actualizar");
        actualizarBtn.setActionCommand("");
        actualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtnActionPerformed(evt);
            }
        });

        textAreaDescripcion.setColumns(20);
        textAreaDescripcion.setRows(5);
        textAreaDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        jScrollPane1.setViewportView(textAreaDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdProveedor)
                            .addComponent(labelNombre)
                            .addComponent(labelCantidad))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textFieldCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldIdProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(actualizarBtn)
                        .addGap(40, 40, 40)
                        .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(textFieldIdProducto)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(labelPrecio)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantidad)
                    .addComponent(labelIdProducto)
                    .addComponent(textFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdProveedor)
                    .addComponent(textFieldIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarBtn)
                    .addComponent(buscarBtn)
                    .addComponent(actualizarBtn))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        String nombre = textFieldNombre.getText();
        String precio = textFieldPrecio.getText();
        String cantidad = textFieldCantidad.getText();
        String idProducto = textFieldIdProducto.getText();
        String idProveedor = textFieldIdProveedor.getText();
        String descripcion = textAreaDescripcion.getText();

        boolean productoAgregado = false;
        try {
            productoAgregado = controlInventario.agregarProducto(nombre, descripcion, Integer.parseInt(precio),
                    Integer.parseInt(cantidad), Integer.parseInt(idProducto), Integer.parseInt(idProveedor));
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
        }

        if (productoAgregado) {
            JOptionPane.showMessageDialog(this, "El producto ha sido agregado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No fue posible agregar el producto al inventario");
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        // TODO add your handling code here:
        String id = textFieldIdProducto.getText();
        String[] matrizDevuelta = controlInventario.buscar(Integer.parseInt(id));

        if (matrizDevuelta != null) {
            textFieldIdProducto.setText(matrizDevuelta[0]);     
            textFieldNombre.setText(matrizDevuelta[1]);
            textAreaDescripcion.setText(matrizDevuelta[2]);
            textFieldPrecio.setText(matrizDevuelta[3]);
            textFieldCantidad.setText(matrizDevuelta[4]);
            textFieldIdProveedor.setText(matrizDevuelta[5]);
                  
        } else {
            JOptionPane.showMessageDialog(this, "No se ha encontrado el producto.");
        }
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void actualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBtnActionPerformed
        // TODO add your handling code here:
        String nombre = textFieldNombre.getText();
        String precio = textFieldPrecio.getText();
        String cantidad = textFieldCantidad.getText();
        String idProducto = textFieldIdProducto.getText();
        String idProveedor = textFieldIdProveedor.getText();
        String descripcion = textAreaDescripcion.getText();

        boolean productoAgregado = false;
        try {
            productoAgregado = controlInventario.actualizar(nombre, descripcion, Integer.parseInt(precio),
                    Integer.parseInt(cantidad), Integer.parseInt(idProducto), Integer.parseInt(idProveedor));
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
        }

        if (productoAgregado) {
            JOptionPane.showMessageDialog(this, "El producto ha sido agregado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No fue posible agregar el producto al inventario");
        }
    }//GEN-LAST:event_actualizarBtnActionPerformed

    public void limpiarCampos() {
        textFieldNombre.setText("");
        textFieldPrecio.setText("");
        textFieldCantidad.setText("");
        textFieldIdProducto.setText("");
        textFieldIdProveedor.setText("");
        textAreaDescripcion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelIdProducto;
    private javax.swing.JLabel labelIdProveedor;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrecio;
    protected javax.swing.JTextArea textAreaDescripcion;
    protected javax.swing.JTextField textFieldCantidad;
    protected javax.swing.JTextField textFieldIdProducto;
    protected javax.swing.JTextField textFieldIdProveedor;
    protected javax.swing.JTextField textFieldNombre;
    protected javax.swing.JTextField textFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
