/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerInventario;
import java.awt.CardLayout;
import java.awt.Component;
//import java.awt.Toolkit; //Importacion para usar el sonido de Windows cuando se presione enter
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicLabelUI;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Leonardo Perdomo
 */
public class FrmViewProductos2 extends javax.swing.JInternalFrame implements KeyListener {

    /**
     * Se declaran los objetos del controlador de la vista relacionada con los
     * productos y el modelo de la tabla que almacena el listado de productos.
     */
    private final ControllerInventario controlInventario;
    DefaultTableModel modeloTablaProductos = new DefaultTableModel();
    private final CardLayout cardLayout;
    
    /**
     * Creates new form FrmViewProductos2
     */
    public FrmViewProductos2() {
        controlInventario = new ControllerInventario();
        initComponents();
        
        
        Component[] components = this.getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JLabel) {
                ((JLabel) component).setUI(new BasicLabelUI());
                ((JLabel) component).setFocusCycleRoot(false);
            }

        }
        cardLayout = (CardLayout) (PanelCards.getLayout());
        textFieldIdProductoC.setText(controlInventario.obtenerId());
        refrescarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        PanelLateral = new javax.swing.JPanel();
        labelCrear = new javax.swing.JLabel();
        labelBuscar = new javax.swing.JLabel();
        labelRegistros = new javax.swing.JLabel();
        PanelCards = new javax.swing.JPanel();
        panelCrear = new javax.swing.JPanel();
        labelTituloCrear = new javax.swing.JLabel();
        labelNombreProductoC = new javax.swing.JLabel();
        labelIdProductoC = new javax.swing.JLabel();
        unidadMedidaCboxC = new javax.swing.JComboBox<>();
        labelUnidadMedidaProductoC = new javax.swing.JLabel();
        textFieldIdProductoC = new javax.swing.JTextField();
        textFieldNombreProductoC = new javax.swing.JTextField();
        agregarBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaDescripcionC = new javax.swing.JTextArea();
        panelRegistros = new javax.swing.JPanel();
        labelTituloRegistros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        panelBuscar = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaDescripcionB = new javax.swing.JTextArea();
        labelTituloBuscar = new javax.swing.JLabel();
        labelIdProductoB = new javax.swing.JLabel();
        textFieldIdProductoB = new javax.swing.JTextField();
        labelNombreProductoB = new javax.swing.JLabel();
        textFieldNombreProductoB = new javax.swing.JTextField();
        unidadMedidaCboxB = new javax.swing.JComboBox<>();
        labelUnidadMedidaProductoB = new javax.swing.JLabel();
        actualizarBtn = new javax.swing.JButton();
        buscarBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jSplitPane1.setDividerLocation(130);
        jSplitPane1.setDividerSize(0);

        PanelLateral.setBackground(new java.awt.Color(204, 204, 204));

        labelCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/añadir-producto-24px.png"))); // NOI18N
        labelCrear.setText("Crear");
        labelCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCrearMouseClicked(evt);
            }
        });

        labelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar-producto-24px.png"))); // NOI18N
        labelBuscar.setText("Buscar");
        labelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarMouseClicked(evt);
            }
        });

        labelRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/registros-24px.png"))); // NOI18N
        labelRegistros.setText("Registros");
        labelRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLateralLayout = new javax.swing.GroupLayout(PanelLateral);
        PanelLateral.setLayout(PanelLateralLayout);
        PanelLateralLayout.setHorizontalGroup(
            PanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLateralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLateralLayout.setVerticalGroup(
            PanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLateralLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(labelCrear)
                .addGap(42, 42, 42)
                .addComponent(labelBuscar)
                .addGap(44, 44, 44)
                .addComponent(labelRegistros)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(PanelLateral);

        PanelCards.setBackground(new java.awt.Color(255, 255, 255));
        PanelCards.setLayout(new java.awt.CardLayout());

        panelCrear.setBackground(new java.awt.Color(255, 255, 255));

        labelTituloCrear.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloCrear.setText("Crear Productos");

        labelNombreProductoC.setText("Nombre:");

        labelIdProductoC.setText("ID:");

        unidadMedidaCboxC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "gr", "Ton", "cm3", "Unidad" }));

        labelUnidadMedidaProductoC.setText("Unidad de Medida:");

        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));

        textAreaDescripcionC.setColumns(20);
        textAreaDescripcionC.setRows(5);
        jScrollPane3.setViewportView(textAreaDescripcionC);

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(agregarBtn)
                    .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelTituloCrear)
                        .addGroup(panelCrearLayout.createSequentialGroup()
                            .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCrearLayout.createSequentialGroup()
                                    .addComponent(labelUnidadMedidaProductoC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(unidadMedidaCboxC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCrearLayout.createSequentialGroup()
                                    .addComponent(labelIdProductoC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldIdProductoC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelNombreProductoC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldNombreProductoC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloCrear)
                .addGap(34, 34, 34)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdProductoC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldIdProductoC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreProductoC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombreProductoC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUnidadMedidaProductoC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadMedidaCboxC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelCards.add(panelCrear, "panelCrear");

        panelRegistros.setBackground(new java.awt.Color(255, 255, 255));

        labelTituloRegistros.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloRegistros.setText("Registros");

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProductos.addKeyListener(this);
        jScrollPane1.setViewportView(tableProductos);

        javax.swing.GroupLayout panelRegistrosLayout = new javax.swing.GroupLayout(panelRegistros);
        panelRegistros.setLayout(panelRegistrosLayout);
        panelRegistrosLayout.setHorizontalGroup(
            panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloRegistros)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelRegistrosLayout.setVerticalGroup(
            panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloRegistros)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        PanelCards.add(panelRegistros, "panelRegistros");

        panelBuscar.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));

        textAreaDescripcionB.setColumns(20);
        textAreaDescripcionB.setRows(5);
        jScrollPane4.setViewportView(textAreaDescripcionB);

        labelTituloBuscar.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloBuscar.setText("Buscar Productos");

        labelIdProductoB.setText("ID:");

        labelNombreProductoB.setText("Nombre:");

        unidadMedidaCboxB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "gr", "Ton", "cm3", "Unidad" }));

        labelUnidadMedidaProductoB.setText("Unidad de Medida:");

        actualizarBtn.setText("Actualizar");
        actualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtnActionPerformed(evt);
            }
        });

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(labelTituloBuscar)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(labelUnidadMedidaProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(unidadMedidaCboxB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(labelIdProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIdProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(labelNombreProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNombreProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buscarBtn)))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(actualizarBtn)))
                .addContainerGap())
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloBuscar)
                .addGap(34, 34, 34)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldIdProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombreProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUnidadMedidaProductoB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadMedidaCboxB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(actualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        PanelCards.add(panelBuscar, "panelBuscar");

        jSplitPane1.setRightComponent(PanelCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        /**
         * Se recoje la informacion de la vista, textfields y combobox
         */
        String nombre = textFieldNombreProductoC.getText();
        String idProducto = textFieldIdProductoC.getText();
        String descripcion = textAreaDescripcionC.getText();
        String unidadMedida = "";

        switch (unidadMedidaCboxC.getSelectedItem().toString()) {
            case "Kg" ->
                unidadMedida = "Kg";
            case "gr" ->
                unidadMedida = "gr";
            case "Ton" ->
                unidadMedida = "Ton";
            case "cm3" ->
                unidadMedida = "cm3";
            case "Unidad" ->
                unidadMedida = "Unidad";
        }

        /**
         * Se crea una variable booleana para determinar si el producto ha sido
         * agregado con exito. Se invoca el metodo agregarProducto del
         * controlador que añade la informacion recopilada a la base de datos en
         * su respectiva tabla.
         */
        boolean productoAgregado = false;
        if (!"".equals(textFieldNombreProductoC.getText())) {
            try {
                productoAgregado = controlInventario.agregarProducto(nombre, descripcion, unidadMedida,
                        Integer.parseInt(idProducto));
                //Se limpian los campos para que quede disponible para rellenar nuevamente
                limpiarCampos(1);
                //Se muestra la tabla con el registro nuevo
                refrescarTabla();
            } catch (Exception e) {
                //Si se presenta un error como el no relleno de los campos, lo muestra
                JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
        }

        if (productoAgregado) {
            //Se muestra un mensaje de exito al crear el producto
            JOptionPane.showMessageDialog(this, "El producto ha sido agregado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No fue posible agregar el producto al inventario.");
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        /**
         * Para buscar un producto en la base de datos, se ingresa la
         * informacion al campo id. Se invoca el metodo buscar en el controlador
         * y este a su vez lo invoca en el modelo, que consulta a base de datos,
         * y los datos devueltos se muestran en los textfields y combobox
         */
        try {
            String id = textFieldIdProductoB.getText();

            String[][] productoEncontrado = controlInventario.buscar(Integer.parseInt(id));
            textFieldIdProductoB.setText(productoEncontrado[0][0]);
            textFieldNombreProductoB.setText(productoEncontrado[0][1]);
            textAreaDescripcionB.setText(productoEncontrado[0][2]);
            unidadMedidaCboxB.setSelectedItem(productoEncontrado[0][3]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se ha ingresado el ID para realizar la busqueda del producto.");
        }
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void actualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBtnActionPerformed
        try {
            String nombre = textFieldNombreProductoB.getText();
            String idProducto = textFieldIdProductoB.getText();
            String descripcion = textAreaDescripcionB.getText();
            String unidadMedida = "";

            switch (unidadMedidaCboxB.getSelectedItem().toString()) {
                case "Kg" ->
                    unidadMedida = "Kg";
                case "gr" ->
                    unidadMedida = "gr";
                case "Ton" ->
                    unidadMedida = "Ton";
                case "cm3" ->
                    unidadMedida = "cm3";
                case "Unidad" ->
                    unidadMedida = "Unidad";
            }

            if (nombre.equals("") || descripcion.equals("")) {
                JOptionPane.showMessageDialog(this, "Por favor realice la busqueda!");
            } else {
                boolean productoActualizado = controlInventario.actualizar(nombre,
                        descripcion, unidadMedida, Integer.parseInt(idProducto), 0, 0, 0);
                limpiarCampos(2);
                refrescarTabla();
                if (productoActualizado) {
                    JOptionPane.showMessageDialog(this, "El producto ha sido actualizado.");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID para realizar una busqueda.");
        }
    }//GEN-LAST:event_actualizarBtnActionPerformed

    private void labelCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCrearMouseClicked
        cardLayout.show(PanelCards, "panelCrear");
    }//GEN-LAST:event_labelCrearMouseClicked

    private void labelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseClicked
        cardLayout.show(PanelCards, "panelBuscar");
    }//GEN-LAST:event_labelBuscarMouseClicked

    private void labelRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrosMouseClicked
        cardLayout.show(PanelCards, "panelRegistros");
    }//GEN-LAST:event_labelRegistrosMouseClicked

    public void limpiarCampos(int opcion) {
        //Metodo para limpiar los campos de los paneles de la vista.
        switch (opcion) {
            case 1 -> {
                textFieldNombreProductoC.setText("");
                textFieldIdProductoC.setText("");
                textAreaDescripcionC.setText("");
                textFieldIdProductoC.setText(controlInventario.obtenerId());
            }
            case 2 -> {
                textFieldNombreProductoB.setText("");
                textFieldIdProductoB.setText("");
                textAreaDescripcionB.setText("");
            }
        }

    }
    
    public final void refrescarTabla() {
        //Se establecen los elementos de la cabecera de la tabla
        String[] cabeceraProducto = {"Id", "Nombre", "Unidad de Medida", "Descripcion"};
        //Se recogen los datos de los clientes añadidos en el almacenamiento temporal
        String[][] matrizProducto = controlInventario.refrescarTablaProducto();
        //Se agregan los datos y la cabecera de la tabla al modelo
        modeloTablaProductos.setDataVector(matrizProducto, cabeceraProducto);
        //Se agrega el modelo a la vista
        tableProductos.setModel(modeloTablaProductos);
        if (tableProductos.getColumnModel().getColumnCount() > 0) {
            tableProductos.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableProductos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tableProductos.getColumnModel().getColumn(3).setPreferredWidth(300);
        }
    }

    /**
     *
     * Los metodos a continuacion sirven para detectar cuando ha sido presionada
     * la tecla enter dentro de la tabla que lista los productos, para permitir
     * actualizarlos.
     */
    public void keyTyped(KeyEvent e) {
    }

    public void keyReleased(KeyEvent e) {
    }

    public void keyPressed(KeyEvent e) {
        int key = e.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            //Toolkit.getDefaultToolkit().beep();
            System.out.println("ENTER Presionado");
            int id = Integer.parseInt((String) modeloTablaProductos.getValueAt(tableProductos.getSelectedRow(), 0));
            String[][] productoEncontrado = controlInventario.buscar(id);
            textFieldIdProductoB.setText(productoEncontrado[0][0]);
            textFieldNombreProductoB.setText(productoEncontrado[0][1]);
            textAreaDescripcionB.setText(productoEncontrado[0][2]);
            unidadMedidaCboxB.setSelectedItem(productoEncontrado[0][3]);
            //Linea para seleccionar una de las pestañas del jTabbedPane
            //jTabbedPane1.setSelectedIndex(1);
            cardLayout.show(PanelCards, "panelBuscar");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCards;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelCrear;
    private javax.swing.JLabel labelIdProductoB;
    private javax.swing.JLabel labelIdProductoC;
    private javax.swing.JLabel labelNombreProductoB;
    private javax.swing.JLabel labelNombreProductoC;
    private javax.swing.JLabel labelRegistros;
    private javax.swing.JLabel labelTituloBuscar;
    private javax.swing.JLabel labelTituloCrear;
    private javax.swing.JLabel labelTituloRegistros;
    private javax.swing.JLabel labelUnidadMedidaProductoB;
    private javax.swing.JLabel labelUnidadMedidaProductoC;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelRegistros;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextArea textAreaDescripcionB;
    private javax.swing.JTextArea textAreaDescripcionC;
    private javax.swing.JTextField textFieldIdProductoB;
    private javax.swing.JTextField textFieldIdProductoC;
    private javax.swing.JTextField textFieldNombreProductoB;
    private javax.swing.JTextField textFieldNombreProductoC;
    private javax.swing.JComboBox<String> unidadMedidaCboxB;
    private javax.swing.JComboBox<String> unidadMedidaCboxC;
    // End of variables declaration//GEN-END:variables
}
