/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Producto;
import Controller.*;
import java.awt.AWTException;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicLabelUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Leonardo Perdomo
 */
public class FrmViewPedidos2 extends javax.swing.JInternalFrame {

    private final CardLayout cardLayout;
    private final ControllerPedidos controlPedidos;
    private final ControllerInventario controlInventario;
    private final DefaultTableModel modeloTablaPedido;
    private ArrayList<Producto> tablaPro;

    /**
     * Creates new form FrmViewPedidos2
     */
    public FrmViewPedidos2() {

        controlPedidos = new ControllerPedidos();
        controlInventario = new ControllerInventario();
        modeloTablaPedido = new DefaultTableModel();
        tablaPro = new ArrayList();

        initComponents();

        Component[] components = this.getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JLabel) {
                ((JLabel) component).setUI(new BasicLabelUI());
                ((JLabel) component).setFocusCycleRoot(false);
            }

        }
        cardLayout = (CardLayout) (panelCards.getLayout());
        textFieldIdPedidoCrear.setText(controlPedidos.obtenerId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelLateral = new javax.swing.JPanel();
        labelCrear = new javax.swing.JLabel();
        labelBuscar = new javax.swing.JLabel();
        labelRegistros = new javax.swing.JLabel();
        panelCards = new javax.swing.JPanel();
        panelCrear = new javax.swing.JPanel();
        labelIdPedidoCrear = new javax.swing.JLabel();
        labelIdClienteCrear = new javax.swing.JLabel();
        labelIdVendedorCrear = new javax.swing.JLabel();
        textFieldIdClienteCrear = new javax.swing.JTextField();
        textFieldIdVendedorCrear = new javax.swing.JTextField();
        labelEstadoPedidoCrear = new javax.swing.JLabel();
        labelNombreClienteCrear = new javax.swing.JLabel();
        textFieldNombreClienteCrear = new javax.swing.JTextField();
        textFieldEstadoPedidoCrear = new javax.swing.JTextField();
        btnCrearPedido = new javax.swing.JButton();
        labelTituloCrear = new javax.swing.JLabel();
        textFieldIdPedidoCrear = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePedidosCrear = new javax.swing.JTable();
        crearProductoBtn = new javax.swing.JButton();
        panelBuscar = new javax.swing.JPanel();
        labelIdPedidoBuscar = new javax.swing.JLabel();
        textFieldIDBuscar = new javax.swing.JTextField();
        labelTituloBuscar = new javax.swing.JLabel();
        btnBuscarPedido = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePedidoBuscar = new javax.swing.JTable();
        panelRegistros = new javax.swing.JPanel();
        labelTipoPersonaRegistros = new javax.swing.JLabel();
        cBoxTipoPersonaRegistros = new javax.swing.JComboBox<>();
        labelTituloRegistros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistros = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(740, 600));

        jSplitPane1.setDividerSize(0);

        panelLateral.setBackground(new java.awt.Color(204, 204, 204));
        panelLateral.setPreferredSize(new java.awt.Dimension(100, 442));

        labelCrear.setBackground(new java.awt.Color(0, 0, 0));
        labelCrear.setIcon(new javax.swing.ImageIcon("C:\\Users\\lperd\\Documents\\NetBeansProjects\\PB-C2\\Reto-PB-C2\\src\\Resources\\clipboard-24px.png")); // NOI18N
        labelCrear.setText("Crear");
        labelCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCrear.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelCrear.setPreferredSize(new java.awt.Dimension(150, 42));
        labelCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCrearMouseClicked(evt);
            }
        });

        labelBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\lperd\\Documents\\NetBeansProjects\\PB-C2\\Reto-PB-C2\\src\\Resources\\search-order-24px.png")); // NOI18N
        labelBuscar.setText("Buscar");
        labelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBuscar.setPreferredSize(new java.awt.Dimension(150, 42));
        labelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarMouseClicked(evt);
            }
        });

        labelRegistros.setIcon(new javax.swing.ImageIcon("C:\\Users\\lperd\\Documents\\NetBeansProjects\\PB-C2\\Reto-PB-C2\\src\\Resources\\lista-de-verificacion-24px.png")); // NOI18N
        labelRegistros.setText("Registros");
        labelRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRegistros.setPreferredSize(new java.awt.Dimension(150, 42));
        labelRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(labelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(labelRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelLateral);

        panelCards.setBackground(new java.awt.Color(204, 204, 204));
        panelCards.setPreferredSize(new java.awt.Dimension(200, 442));
        panelCards.setLayout(new java.awt.CardLayout());

        labelIdPedidoCrear.setText("ID Pedido:");
        labelIdPedidoCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelIdClienteCrear.setText("Cod Cliente:");
        labelIdClienteCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelIdVendedorCrear.setText("Cod Vendedor:");
        labelIdVendedorCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldIdClienteCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldIdVendedorCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        labelEstadoPedidoCrear.setText("Estado del Pedido:");
        labelEstadoPedidoCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        labelNombreClienteCrear.setText("Nombre Cliente:");
        labelNombreClienteCrear.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldNombreClienteCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        textFieldEstadoPedidoCrear.setPreferredSize(new java.awt.Dimension(150, 22));

        btnCrearPedido.setText("Crear");

        labelTituloCrear.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloCrear.setText("Crear Pedidos");

        tablePedidosCrear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre", "Unidad", "Cantidad", "Precio de Venta", "Total Parcial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePedidosCrear.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablePedidosCrear.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePedidosCrear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablePedidosCrearKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablePedidosCrear);
        if (tablePedidosCrear.getColumnModel().getColumnCount() > 0) {
            tablePedidosCrear.getColumnModel().getColumn(0).setResizable(false);
            tablePedidosCrear.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablePedidosCrear.getColumnModel().getColumn(1).setResizable(false);
            tablePedidosCrear.getColumnModel().getColumn(1).setPreferredWidth(190);
        }

        crearProductoBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\lperd\\Documents\\NetBeansProjects\\PB-C2\\Reto-PB-C2\\src\\Resources\\anadir-producto-24px.png")); // NOI18N
        crearProductoBtn.setToolTipText("Agregar Producto");
        crearProductoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearProductoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProductoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addComponent(btnCrearPedido))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelTituloCrear))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelIdPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIdPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEstadoPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldEstadoPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelIdClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIdClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNombreClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldNombreClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelIdVendedorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIdVendedorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(crearProductoBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelTituloCrear)
                        .addGap(31, 31, 31)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(textFieldIdPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEstadoPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEstadoPedidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelIdClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIdClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIdVendedorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIdVendedorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNombreClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crearProductoBtn)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCards.add(panelCrear, "panelCrear");

        labelIdPedidoBuscar.setText("ID Pedido:");
        labelIdPedidoBuscar.setPreferredSize(new java.awt.Dimension(110, 16));

        textFieldIDBuscar.setPreferredSize(new java.awt.Dimension(150, 22));

        labelTituloBuscar.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloBuscar.setText("Buscar Pedido");

        btnBuscarPedido.setText("Buscar");

        tablePedidoBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Cliente", "ID Vendedor", "Total "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablePedidoBuscar);

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelTituloBuscar))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btnBuscarPedido))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBuscarLayout.createSequentialGroup()
                                .addComponent(labelIdPedidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIDBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloBuscar)
                .addGap(33, 33, 33)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelIdPedidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarPedido)
                        .addComponent(textFieldIDBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCards.add(panelBuscar, "panelBuscar");

        labelTipoPersonaRegistros.setText("Tipo de Persona:");
        labelTipoPersonaRegistros.setPreferredSize(new java.awt.Dimension(110, 16));

        cBoxTipoPersonaRegistros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Vendedor", "Proveedor" }));
        cBoxTipoPersonaRegistros.setSelectedIndex(cBoxTipoPersonaRegistros.getSelectedIndex());
        cBoxTipoPersonaRegistros.setPreferredSize(new java.awt.Dimension(150, 22));
        cBoxTipoPersonaRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTipoPersonaRegistrosActionPerformed(evt);
            }
        });

        labelTituloRegistros.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        labelTituloRegistros.setText("RegistrosTerceros");

        tableRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Direccion", "Telefono", "Correo", "Ciudad", "Departamento", "Tipo de Documento", "No. Documento"
            }
        ));
        tableRegistros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tableRegistros);

        javax.swing.GroupLayout panelRegistrosLayout = new javax.swing.GroupLayout(panelRegistros);
        panelRegistros.setLayout(panelRegistrosLayout);
        panelRegistrosLayout.setHorizontalGroup(
            panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloRegistros)
                    .addComponent(labelTipoPersonaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegistrosLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(cBoxTipoPersonaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegistrosLayout.setVerticalGroup(
            panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloRegistros)
                .addGap(27, 27, 27)
                .addGroup(panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTipoPersonaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxTipoPersonaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelCards.add(panelRegistros, "panelRegistros");

        jSplitPane1.setRightComponent(panelCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCrearMouseClicked
        cardLayout.show(panelCards, "panelCrear");
    }//GEN-LAST:event_labelCrearMouseClicked

    private void labelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseClicked
        cardLayout.show(panelCards, "panelBuscar");
    }//GEN-LAST:event_labelBuscarMouseClicked


    private void labelRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrosMouseClicked
        /*
        cardLayout.show(panelCards, "panelRegistros");
        cBoxTipoPersonaRegistros.setSelectedIndex(cBoxTipoPersonaRegistros.getSelectedIndex());
        String persona = cBoxTipoPersonaRegistros.getSelectedItem().toString();
        switch (persona) {
            case "Cliente" -> {
                refrescarTabla(1);
            }
            case "Vendedor" -> {
                refrescarTabla(2);
            }
            case "Proveedor" -> {
                refrescarTabla(3);
            }
        }
         */
    }//GEN-LAST:event_labelRegistrosMouseClicked


    private void cBoxTipoPersonaRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTipoPersonaRegistrosActionPerformed
        /*
        String persona = cBoxTipoPersonaRegistros.getSelectedItem().toString();
        switch (persona) {
            case "Cliente" -> {
                refrescarTabla(1);
            }   
            case "Vendedor" -> {
                refrescarTabla(2);
            }
            case "Proveedor" -> {
                refrescarTabla(3);
            }
        }
         */
    }//GEN-LAST:event_cBoxTipoPersonaRegistrosActionPerformed

    private void tablePedidosCrearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablePedidosCrearKeyPressed
        // TODO add your handling code here:
        try {
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_TAB) {
                //Pregunta si el cursor se encuentra en la columna de ID para agregar los productos
                if (tablePedidosCrear.getSelectedColumn() == 0) {
                    if (tablePedidosCrear.isEditing()) {
                        tablePedidosCrear.getCellEditor().stopCellEditing();
                    }
                    Toolkit.getDefaultToolkit().beep();
                    System.out.println("TAB Presionado");
                    int filaSeleccionada = tablePedidosCrear.getSelectedRow();
                    //int columnaSeleccionada = tablePedidosCrear.getSelectedColumn();
                    String codigo = tablePedidosCrear.getValueAt(filaSeleccionada, 0).toString();
                    //String idPedido = textFieldIdPedidoCrear.getText();
                    //boolean productoAgregado = false;
                    try {
                        String[][] productoDevuelto = controlInventario.buscar(Integer.parseInt(codigo));
                        controlPedidos.agregarProducto(productoDevuelto);
                    } catch (Exception e) {
                        e.getMessage();
                    }

                    refrescarTabla(1);
                }

            }

            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                //Si al presionar la tecla Enter la celda en cuestion esta siendo editada,
                //detiene la edicion y realiza la accion.
                if (tablePedidosCrear.isEditing()) {
                    tablePedidosCrear.getCellEditor().stopCellEditing();
                }

                System.out.println("ENTER Presionado");
                int columna = tablePedidosCrear.getSelectedColumn();
                if (columna == 4) {
                    //Se calcula el precio total del producto entre cantidad y precio unitario
                    int fila = tablePedidosCrear.getSelectedRow();
                    String cantidad = tablePedidosCrear.getValueAt(fila, 3).toString();
                    String precio = tablePedidosCrear.getValueAt(fila, 4).toString();
                    int total = Integer.parseInt(cantidad) * Integer.parseInt(precio);
                    tablePedidosCrear.setValueAt(Integer.toString(total), fila, 5);
                    //Se agrega una fila en blanco para introducir la informacion del siguiente producto                    
                    tablePedidosCrear.changeSelection(fila, 3, false, false);
                }
            }

        } catch (Exception e) {
            e.getMessage();
        }

    }//GEN-LAST:event_tablePedidosCrearKeyPressed

    private void crearProductoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductoBtnActionPerformed
        int filaSeleccionada = tablePedidosCrear.getSelectedRow();
        String codigoProducto = tablePedidosCrear.getValueAt(filaSeleccionada, 0).toString();
        String idPedido = textFieldIdPedidoCrear.getText();

        boolean productoAgregado = false;
        try {
            productoAgregado = controlPedidos.agregarProducto(codigoProducto, idPedido);
        } catch (Exception e) {
            e.getMessage();
        }
        if (productoAgregado) {

            refrescarTabla(1);
        }

//        String[][] productoEncontrado = controlInventario.buscar(Integer.parseInt(codigo));
//        String[][] pro = new String[1][3];
//        pro[0][0] = productoEncontrado[0][0];
//        pro[0][1] = productoEncontrado[0][1];
//        pro[0][2] = productoEncontrado[0][3];
//        refrescarTabla(2, pro);

    }//GEN-LAST:event_crearProductoBtnActionPerformed

    public void refrescarTabla(int opcion) {

        switch (opcion) {
            case 1 -> {
                //Se establecen los elementos de la cabecera de la tabla
                String[] cabeceraPedido = {"Id", "Nombre", "Unidad", "Cantidad", "Precio", "Total Parcial"};
                //Se recogen los datos de los clientes añadidos en el almacenamiento temporal
                String[][] matrizPedido = controlPedidos.refrescarTablaPedidos();
                //Se agregan los datos y la cabecera de la tabla al modelo
                modeloTablaPedido.setDataVector(matrizPedido, cabeceraPedido);
                //Se agrega el modelo a la vista
                modeloTablaPedido.addRow(new String[]{"", ""});
                tablePedidosCrear.setModel(modeloTablaPedido);
                if (tablePedidosCrear.getColumnModel().getColumnCount() > 0) {
                    tablePedidosCrear.getColumnModel().getColumn(0).setPreferredWidth(60);
                    tablePedidosCrear.getColumnModel().getColumn(1).setPreferredWidth(190);
                }
                tablePedidosCrear.changeSelection(tablePedidosCrear.getRowCount() - 1, -1, false, false);
            }
            case 2 -> {
//                String[] cabeceraInventario = {"Id", "Nombre", "Unidad", "Cantidad", "Precio", "Total Parcial"};
//
//                modeloTablaPedido.setDataVector(registro, cabeceraInventario);
//                modeloTablaPedido.addRow(new String[]{"", ""});
//                tablePedidosCrear.setModel(modeloTablaPedido);
//                if (tablePedidosCrear.getColumnModel().getColumnCount() > 0) {
//                    tablePedidosCrear.getColumnModel().getColumn(0).setPreferredWidth(30);
//                    tablePedidosCrear.getColumnModel().getColumn(1).setPreferredWidth(120);
//                }
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPedido;
    private javax.swing.JButton btnCrearPedido;
    private javax.swing.JComboBox<String> cBoxTipoPersonaRegistros;
    private javax.swing.JButton crearProductoBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelCrear;
    private javax.swing.JLabel labelEstadoPedidoCrear;
    private javax.swing.JLabel labelIdClienteCrear;
    private javax.swing.JLabel labelIdPedidoBuscar;
    private javax.swing.JLabel labelIdPedidoCrear;
    private javax.swing.JLabel labelIdVendedorCrear;
    private javax.swing.JLabel labelNombreClienteCrear;
    private javax.swing.JLabel labelRegistros;
    private javax.swing.JLabel labelTipoPersonaRegistros;
    private javax.swing.JLabel labelTituloBuscar;
    private javax.swing.JLabel labelTituloCrear;
    private javax.swing.JLabel labelTituloRegistros;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelRegistros;
    private javax.swing.JTable tablePedidoBuscar;
    private javax.swing.JTable tablePedidosCrear;
    private javax.swing.JTable tableRegistros;
    private javax.swing.JTextField textFieldEstadoPedidoCrear;
    private javax.swing.JTextField textFieldIDBuscar;
    private javax.swing.JTextField textFieldIdClienteCrear;
    private javax.swing.JTextField textFieldIdPedidoCrear;
    private javax.swing.JTextField textFieldIdVendedorCrear;
    private javax.swing.JTextField textFieldNombreClienteCrear;
    // End of variables declaration//GEN-END:variables
}
