/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.*;
import Controller.*;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo Perdomo
 */
public class FrmView extends javax.swing.JFrame {

    ControllerCliente controlCliente;
    List<Cliente> listaClientes = new ArrayList<>();

    /**
     * Creates new form FrmView
     */
    public FrmView() {
        controlCliente = new ControllerCliente();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelClientes = new javax.swing.JPanel();
        panelListaClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listClientes = new javax.swing.JList<>();
        Nombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Ciudad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldDireccion = new javax.swing.JTextField();
        textFieldTelefono = new javax.swing.JTextField();
        textFieldCorreo = new javax.swing.JTextField();
        textFieldCiudad = new javax.swing.JTextField();
        textFieldDepartamento = new javax.swing.JTextField();
        textFieldNroDocumento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        Id = new javax.swing.JLabel();
        textFieldFecha = new javax.swing.JTextField();
        crearClienteBtn = new javax.swing.JButton();
        leerClienteBtn = new javax.swing.JButton();
        actualizarClienteBtn = new javax.swing.JButton();
        borrarClienteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor");
        setPreferredSize(new java.awt.Dimension(612, 540));
        setResizable(false);

        panelClientes.setPreferredSize(new java.awt.Dimension(596, 490));

        listClientes.setToolTipText("");
        jScrollPane1.setViewportView(listClientes);

        javax.swing.GroupLayout panelListaClientesLayout = new javax.swing.GroupLayout(panelListaClientes);
        panelListaClientes.setLayout(panelListaClientesLayout);
        panelListaClientesLayout.setHorizontalGroup(
            panelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(panelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelListaClientesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelListaClientesLayout.setVerticalGroup(
            panelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
            .addGroup(panelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelListaClientesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        Nombre.setText("Nombre:");

        jLabel3.setText("Direccion:");

        Telefono.setText("Telefono:");

        Correo.setText("Correo:");

        Ciudad.setText("Ciudad: ");

        jLabel7.setText("Departamento:");

        jLabel9.setText("Nro Documento:");

        jLabel10.setText("Fecha de Nacimiento:");

        Id.setText("ID:");

        crearClienteBtn.setText("Crear");
        crearClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteBtnActionPerformed(evt);
            }
        });

        leerClienteBtn.setText("Leer");
        leerClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerClienteBtnActionPerformed(evt);
            }
        });

        actualizarClienteBtn.setText("Actualizar");
        actualizarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarClienteBtnActionPerformed(evt);
            }
        });

        borrarClienteBtn.setText("Borrar");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(crearClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(leerClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(actualizarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(borrarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Telefono)
                                .addComponent(Ciudad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Id, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textFieldNroDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textFieldCiudad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(Correo)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(panelListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(textFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono)
                    .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ciudad)
                    .addComponent(textFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo)
                    .addComponent(textFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id)
                    .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(textFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textFieldNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(panelListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearClienteBtn)
                    .addComponent(leerClienteBtn)
                    .addComponent(actualizarClienteBtn)
                    .addComponent(borrarClienteBtn))
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Cliente", panelClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteBtnActionPerformed
        String nombre = textFieldNombre.getText();
        String direccion = textFieldDireccion.getText();
        String telefono = textFieldTelefono.getText();
        String correo = textFieldCorreo.getText();
        String ciudad = textFieldCiudad.getText();
        String departamento = textFieldDepartamento.getText();
        String tipoDocumento = "";
        String nroDocumento = textFieldNroDocumento.getText();
        String fechaNacimiento = textFieldFecha.getText();
        String id = textFieldId.getText();

        boolean fidelizacion = true;
        boolean clienteCreado = false;
        try {
            clienteCreado = controlCliente.crear(nombre, direccion, telefono, correo,
                    ciudad, departamento, tipoDocumento, Integer.parseInt(nroDocumento), fechaNacimiento,
                    Integer.parseInt(id), 0, listaClientes);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
        }

        if (clienteCreado) {
            JOptionPane.showMessageDialog(this, "El cliente ha sido creado exitosamente.");
        }

        limpiarCamposCliente();
        refrescarListaCliente();

    }//GEN-LAST:event_crearClienteBtnActionPerformed

    private void leerClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerClienteBtnActionPerformed
        Cliente cliente = null;
        try {
            int id = Integer.parseInt(textFieldId.getText());
            cliente = controlCliente.leer(id, listaClientes);
            if (cliente != null) {
                textFieldNombre.setText(cliente.getNombre());
                textFieldDireccion.setText(cliente.getDireccion());
                textFieldTelefono.setText(cliente.getTelefono());
                textFieldCorreo.setText(cliente.getCorreo());
                textFieldCiudad.setText(cliente.getCiudad());
                textFieldDepartamento.setText(cliente.getDepartamento());
                textFieldNroDocumento.setText(Integer.toString(cliente.getNroDocumento()));
                textFieldFecha.setText(cliente.getFechaNacimiento());
            } else {
                JOptionPane.showMessageDialog(this, "No se ha encontrado el cliente.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Rellene el campo ID.");
        }
    }//GEN-LAST:event_leerClienteBtnActionPerformed

    private void actualizarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarClienteBtnActionPerformed

        try {
            int id = Integer.parseInt(textFieldId.getText());
            String nombre = textFieldNombre.getText();
            String direccion = textFieldDireccion.getText();
            String telefono = textFieldTelefono.getText();
            String correo = textFieldCorreo.getText();
            String ciudad = textFieldCiudad.getText();
            String departamento = textFieldDepartamento.getText();
            String tipoDocumento = "";
            String nroDocumento = textFieldNroDocumento.getText();
            String fechaNacimiento = textFieldFecha.getText();

            boolean clienteActualizado = false;
            try {
                clienteActualizado = controlCliente.actualizar(nombre, direccion, telefono, correo,
                        ciudad, departamento, tipoDocumento, Integer.parseInt(nroDocumento), fechaNacimiento,
                        id, 0, listaClientes);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Cliente no existe.");
            }

            if (clienteActualizado) {
                JOptionPane.showMessageDialog(this, "El cliente ha sido actualizado exitosamente.");
            }
            limpiarCamposCliente();
            refrescarListaCliente();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
        }

    }//GEN-LAST:event_actualizarClienteBtnActionPerformed

    public void limpiarCamposCliente() {
        //Se limpian los textField
        textFieldNombre.setText("");
        textFieldDireccion.setText("");
        textFieldTelefono.setText("");
        textFieldCorreo.setText("");
        textFieldCiudad.setText("");
        textFieldDepartamento.setText("");
        textFieldNroDocumento.setText("");
        textFieldId.setText("");
        textFieldFecha.setText("");

    }

    //Método que se encarga de actualizar la lista del tab lista de Agentes
    public void refrescarListaCliente() {
        //Se define un modelo de lista para almacenar los datos a listar en el tab lista de clientes
        DefaultListModel model = new DefaultListModel();

        //Ciclo que recorre los elementos existentes en la lista de estudiantes para ir agregándolos en el tab lista estudiantes
        for (int i = 0; i < listaClientes.size(); i++) {
            /*
            * listaEstudiantes.get(i): Significa que accedo al elemento de la lista en posición 'i'.
            * Al ser una lista de objetos de tipo Estudiante, en cada iteración del ciclo se accede a cada estudiante
             */
            Cliente cliente = listaClientes.get(i);

            //Se agrega la información requerida al modelo de lista
            model.add(i, cliente.toString());
        }

        //El modelo es enviado al tab lista de vuelos en el elemento de tipo jList 'lstFlight'
        listClientes.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ciudad;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Telefono;
    private javax.swing.JButton actualizarClienteBtn;
    private javax.swing.JButton borrarClienteBtn;
    private javax.swing.JButton crearClienteBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton leerClienteBtn;
    private javax.swing.JList<String> listClientes;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelListaClientes;
    private javax.swing.JTextField textFieldCiudad;
    private javax.swing.JTextField textFieldCorreo;
    private javax.swing.JTextField textFieldDepartamento;
    private javax.swing.JTextField textFieldDireccion;
    private javax.swing.JTextField textFieldFecha;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldNroDocumento;
    private javax.swing.JTextField textFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
