/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.*;
import Controller.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo Perdomo
 */
public class FrmView extends javax.swing.JFrame {

    private final ControllerCliente controlCliente;
    private final ControllerVendedor controlVendedor;
    private final ArrayList<Proveedor> tablaProveedores = new ArrayList<>();
    
    DefaultTableModel modeloTablaCliente = new DefaultTableModel();
    DefaultTableModel modeloTablaVendedor = new DefaultTableModel();
    DefaultTableModel modeloTablaProveedor = new DefaultTableModel();

    /**
     * Creates new form FrmView
     */
    public FrmView() {
        controlCliente = new ControllerCliente();
        controlVendedor = new ControllerVendedor();
        /*
        try {
            setUIFont(new javax.swing.plaf.FontUIResource("Helvetica", Font.PLAIN, 18));
        } catch (Exception e) {

        }*/

        //this.setLocation(0,0);
        initComponents();
        //setModeloTablas();
    }

    //Metodo para cambiar la fuente del jFrame
    public static void setUIFont(javax.swing.plaf.FontUIResource f) {
        java.util.Enumeration keys = UIManager.getDefaults().keys();
        while (keys.hasMoreElements()) {
            Object key = keys.nextElement();
            Object value = UIManager.get(key);
            if (value instanceof javax.swing.plaf.FontUIResource) {
                UIManager.put(key, f);
            }
        }
    }

// ...
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTDocCliente = new javax.swing.ButtonGroup();
        buttonGroupTDocVendedor = new javax.swing.ButtonGroup();
        buttonGroupTDocProveedor = new javax.swing.ButtonGroup();
        tabbedPanelGestor = new javax.swing.JTabbedPane();
        panelClientes = new javax.swing.JPanel();
        NombreCliente = new javax.swing.JLabel();
        DireccionCliente = new javax.swing.JLabel();
        TelefonoCliente = new javax.swing.JLabel();
        CorreoCliente = new javax.swing.JLabel();
        CiudadCliente = new javax.swing.JLabel();
        DepartamentoCliente = new javax.swing.JLabel();
        NroDocumentoCliente = new javax.swing.JLabel();
        textFieldNombreCliente = new javax.swing.JTextField();
        textFieldDireccionCliente = new javax.swing.JTextField();
        textFieldTelefonoCliente = new javax.swing.JTextField();
        textFieldCorreoCliente = new javax.swing.JTextField();
        textFieldCiudadCliente = new javax.swing.JTextField();
        textFieldDepartamentoCliente = new javax.swing.JTextField();
        textFieldNroDocumentoCliente = new javax.swing.JTextField();
        FechaNacimientoCliente = new javax.swing.JLabel();
        textFieldIdCliente = new javax.swing.JTextField();
        IdCliente = new javax.swing.JLabel();
        textFieldFechaCliente = new javax.swing.JTextField();
        crearClienteBtn = new javax.swing.JButton();
        leerClienteBtn = new javax.swing.JButton();
        actualizarClienteBtn = new javax.swing.JButton();
        borrarClienteBtn = new javax.swing.JButton();
        TipoDocCliente = new javax.swing.JLabel();
        panelListaCliente = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        radioButtonCCCliente = new javax.swing.JRadioButton();
        radioButtonNITCliente = new javax.swing.JRadioButton();
        radioButtonOtroCliente = new javax.swing.JRadioButton();
        panelVendedor = new javax.swing.JPanel();
        NombreVendedor = new javax.swing.JLabel();
        DireccionVendedor = new javax.swing.JLabel();
        IdVendedor = new javax.swing.JLabel();
        CiudadVendedor = new javax.swing.JLabel();
        TelefonoVendedor = new javax.swing.JLabel();
        TipoDocVendedor = new javax.swing.JLabel();
        NroDocumentoVendedor = new javax.swing.JLabel();
        CorreoVendedor = new javax.swing.JLabel();
        DepartamentoVendedor = new javax.swing.JLabel();
        textFieldNombreVendedor = new javax.swing.JTextField();
        textFieldDireccionVendedor = new javax.swing.JTextField();
        textFieldIdVendedor = new javax.swing.JTextField();
        textFieldCiudadVendedor = new javax.swing.JTextField();
        textFieldTelefonoVendedor = new javax.swing.JTextField();
        textFieldNroDocVendedor = new javax.swing.JTextField();
        textFieldCorreoVendedor = new javax.swing.JTextField();
        textFieldDptoVendedor = new javax.swing.JTextField();
        crearVendedorBtn = new javax.swing.JButton();
        leerVendedorBtn = new javax.swing.JButton();
        actualizarVendedorBtn = new javax.swing.JButton();
        borrarVendedorBtn = new javax.swing.JButton();
        panelListaVendedor = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableVendedor = new javax.swing.JTable();
        radioButtonCCVendedor = new javax.swing.JRadioButton();
        radioButtonNITVendedor = new javax.swing.JRadioButton();
        radioButtonOtroVendedor = new javax.swing.JRadioButton();
        panelProveedor = new javax.swing.JPanel();
        NombreProveedor = new javax.swing.JLabel();
        DireccionProveedor = new javax.swing.JLabel();
        IdProveedor = new javax.swing.JLabel();
        CiudadProveedor = new javax.swing.JLabel();
        TelefonoProveedor = new javax.swing.JLabel();
        TipoDocProveedor = new javax.swing.JLabel();
        NroDocumentoProveedor = new javax.swing.JLabel();
        CorreoProveedor = new javax.swing.JLabel();
        DepartamentoProveedor = new javax.swing.JLabel();
        textFieldNombreProveedor = new javax.swing.JTextField();
        textFieldDireccionProveedor = new javax.swing.JTextField();
        textFieldIdProveedor = new javax.swing.JTextField();
        textFieldCiudadProveedor = new javax.swing.JTextField();
        textFieldTelefonoProveedor = new javax.swing.JTextField();
        textFieldNroDocProveedor = new javax.swing.JTextField();
        textFieldCorreoProveedor = new javax.swing.JTextField();
        textFieldDptoProveedor = new javax.swing.JTextField();
        crearProveedorBtn = new javax.swing.JButton();
        leerProveedorBtn = new javax.swing.JButton();
        actualizarProveedorBtn = new javax.swing.JButton();
        borrarProveedorBtn = new javax.swing.JButton();
        panelListaProveedor = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableProveedor = new javax.swing.JTable();
        radioButtonCCProveedor = new javax.swing.JRadioButton();
        radioButtonNITProveedor = new javax.swing.JRadioButton();
        radioButtonOtroProveedor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor");
        setPreferredSize(new java.awt.Dimension(600, 540));
        setResizable(false);

        tabbedPanelGestor.setToolTipText("");
        tabbedPanelGestor.setPreferredSize(new java.awt.Dimension(595, 530));

        panelClientes.setPreferredSize(new java.awt.Dimension(596, 490));

        NombreCliente.setText("Nombre:");

        DireccionCliente.setText("Direccion:");

        TelefonoCliente.setText("Telefono:");

        CorreoCliente.setText("Correo:");

        CiudadCliente.setText("Ciudad: ");

        DepartamentoCliente.setText("Departamento:");

        NroDocumentoCliente.setText("Nro Documento:");

        FechaNacimientoCliente.setText("Fecha de Nacimiento:");

        IdCliente.setText("Id:");

        crearClienteBtn.setText("Crear");
        crearClienteBtn.setToolTipText("Llena el formulario para crear un cliente nuevo");
        crearClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteBtnActionPerformed(evt);
            }
        });

        leerClienteBtn.setText("Buscar");
        leerClienteBtn.setToolTipText("Ingresa un numero de id para buscar un cliente registrado");
        leerClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerClienteBtnActionPerformed(evt);
            }
        });

        actualizarClienteBtn.setText("Actualizar");
        actualizarClienteBtn.setToolTipText("Actualiza la información de un cliente registrado");
        actualizarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarClienteBtnActionPerformed(evt);
            }
        });

        borrarClienteBtn.setText("Borrar");

        TipoDocCliente.setText("Tipo Doc:");

        panelListaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelListaCliente.setPreferredSize(new java.awt.Dimension(540, 180));

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane6.setViewportView(tableCliente);

        javax.swing.GroupLayout panelListaClienteLayout = new javax.swing.GroupLayout(panelListaCliente);
        panelListaCliente.setLayout(panelListaClienteLayout);
        panelListaClienteLayout.setHorizontalGroup(
            panelListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        panelListaClienteLayout.setVerticalGroup(
            panelListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        buttonGroupTDocCliente.add(radioButtonCCCliente);
        radioButtonCCCliente.setSelected(true);
        radioButtonCCCliente.setText("C.C");

        buttonGroupTDocCliente.add(radioButtonNITCliente);
        radioButtonNITCliente.setText("NIT");

        buttonGroupTDocCliente.add(radioButtonOtroCliente);
        radioButtonOtroCliente.setText("Otro");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdCliente)
                            .addComponent(DireccionCliente)
                            .addComponent(NombreCliente)
                            .addComponent(CiudadCliente)
                            .addComponent(TelefonoCliente))
                        .addGap(14, 14, 14)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(textFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCiudadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NroDocumentoCliente)
                            .addComponent(CorreoCliente)
                            .addComponent(DepartamentoCliente)
                            .addComponent(FechaNacimientoCliente)
                            .addComponent(TipoDocCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addComponent(radioButtonCCCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonNITCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonOtroCliente)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldNroDocumentoCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFieldCorreoCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFieldDepartamentoCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFieldFechaCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(1, 1, 1))))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(crearClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(leerClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(actualizarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(borrarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelListaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NombreCliente)
                        .addComponent(textFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TipoDocCliente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioButtonCCCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioButtonNITCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioButtonOtroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DireccionCliente)
                            .addComponent(textFieldDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NroDocumentoCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CorreoCliente)
                            .addComponent(textFieldIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldCiudadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CiudadCliente)
                            .addComponent(DepartamentoCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaNacimientoCliente)
                            .addComponent(textFieldTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelefonoCliente)))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addComponent(textFieldNroDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldDepartamentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldFechaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelListaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearClienteBtn)
                    .addComponent(leerClienteBtn)
                    .addComponent(actualizarClienteBtn)
                    .addComponent(borrarClienteBtn))
                .addGap(52, 52, 52))
        );

        tabbedPanelGestor.addTab("Cliente", panelClientes);

        NombreVendedor.setText("Nombre:");

        DireccionVendedor.setText("Direccion:");

        IdVendedor.setText("Id:");

        CiudadVendedor.setText("Ciudad:");

        TelefonoVendedor.setText("Telefono:");

        TipoDocVendedor.setText("Tipo Doc:");

        NroDocumentoVendedor.setText("Nro Documento:");

        CorreoVendedor.setText("Correo:");

        DepartamentoVendedor.setText("Departamento:");

        crearVendedorBtn.setToolTipText("Llena el formulario para crear un vendedor nuevo");
        crearVendedorBtn.setLabel("Crear");
        crearVendedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearVendedorBtnActionPerformed(evt);
            }
        });

        leerVendedorBtn.setText("Leer");
        leerVendedorBtn.setToolTipText("Ingresa un numero de id para buscar un vendedor registrado");
        leerVendedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerVendedorBtnActionPerformed(evt);
            }
        });

        actualizarVendedorBtn.setText("Actualizar");
        actualizarVendedorBtn.setToolTipText("Actualiza la información de un vendedor registrado");
        actualizarVendedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarVendedorBtnActionPerformed(evt);
            }
        });

        borrarVendedorBtn.setText("Borrar");

        panelListaVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Vendedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelListaVendedor.setPreferredSize(new java.awt.Dimension(540, 180));

        tableVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableVendedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane7.setViewportView(tableVendedor);

        javax.swing.GroupLayout panelListaVendedorLayout = new javax.swing.GroupLayout(panelListaVendedor);
        panelListaVendedor.setLayout(panelListaVendedorLayout);
        panelListaVendedorLayout.setHorizontalGroup(
            panelListaVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        panelListaVendedorLayout.setVerticalGroup(
            panelListaVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        buttonGroupTDocVendedor.add(radioButtonCCVendedor);
        radioButtonCCVendedor.setSelected(true);
        radioButtonCCVendedor.setText("C.C");

        buttonGroupTDocVendedor.add(radioButtonNITVendedor);
        radioButtonNITVendedor.setText("NIT");

        buttonGroupTDocVendedor.add(radioButtonOtroVendedor);
        radioButtonOtroVendedor.setText("Otro");

        javax.swing.GroupLayout panelVendedorLayout = new javax.swing.GroupLayout(panelVendedor);
        panelVendedor.setLayout(panelVendedorLayout);
        panelVendedorLayout.setHorizontalGroup(
            panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVendedorLayout.createSequentialGroup()
                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVendedorLayout.createSequentialGroup()
                        .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVendedorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DireccionVendedor)
                                    .addComponent(NombreVendedor)
                                    .addComponent(IdVendedor)
                                    .addComponent(CiudadVendedor)
                                    .addComponent(TelefonoVendedor))
                                .addGap(14, 14, 14)
                                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldDireccionVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldIdVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldCiudadVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldTelefonoVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNombreVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NroDocumentoVendedor)
                                    .addComponent(CorreoVendedor)
                                    .addComponent(DepartamentoVendedor)
                                    .addComponent(TipoDocVendedor))
                                .addGap(35, 35, 35)
                                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelVendedorLayout.createSequentialGroup()
                                        .addComponent(radioButtonCCVendedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioButtonNITVendedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioButtonOtroVendedor)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(textFieldCorreoVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(textFieldNroDocVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(textFieldDptoVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                            .addGroup(panelVendedorLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(crearVendedorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(leerVendedorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(actualizarVendedorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(borrarVendedorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVendedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelListaVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelVendedorLayout.setVerticalGroup(
            panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVendedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonCCVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButtonNITVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButtonOtroVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NombreVendedor)
                        .addComponent(TipoDocVendedor)
                        .addComponent(textFieldNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionVendedor)
                    .addComponent(NroDocumentoVendedor)
                    .addComponent(textFieldDireccionVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNroDocVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdVendedor)
                    .addComponent(CorreoVendedor)
                    .addComponent(textFieldIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCorreoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CiudadVendedor)
                    .addComponent(DepartamentoVendedor)
                    .addComponent(textFieldCiudadVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDptoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoVendedor)
                    .addComponent(textFieldTelefonoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelListaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearVendedorBtn)
                    .addComponent(leerVendedorBtn)
                    .addComponent(actualizarVendedorBtn)
                    .addComponent(borrarVendedorBtn))
                .addGap(52, 52, 52))
        );

        tabbedPanelGestor.addTab("Vendedor", panelVendedor);

        NombreProveedor.setText("Nombre:");

        DireccionProveedor.setText("Direccion:");

        IdProveedor.setText("Id:");

        CiudadProveedor.setText("Ciudad:");

        TelefonoProveedor.setText("Telefono:");

        TipoDocProveedor.setText("Tipo Doc:");

        NroDocumentoProveedor.setText("Nro Documento:");

        CorreoProveedor.setText("Correo:");

        DepartamentoProveedor.setText("Departamento:");

        textFieldNombreProveedor.setToolTipText("");

        crearProveedorBtn.setToolTipText("Llena el formulario para crear un proveedor nuevo");
        crearProveedorBtn.setLabel("Crear");

        leerProveedorBtn.setText("Leer");
        leerProveedorBtn.setToolTipText("Ingresa un numero de id para buscar un proveedor registrado");

        actualizarProveedorBtn.setText("Actualizar");
        actualizarProveedorBtn.setToolTipText("Actualiza la información de un proveedor registrado");

        borrarProveedorBtn.setText("Borrar");

        panelListaProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Proveedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelListaProveedor.setPreferredSize(new java.awt.Dimension(540, 180));

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableProveedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane8.setViewportView(tableProveedor);

        javax.swing.GroupLayout panelListaProveedorLayout = new javax.swing.GroupLayout(panelListaProveedor);
        panelListaProveedor.setLayout(panelListaProveedorLayout);
        panelListaProveedorLayout.setHorizontalGroup(
            panelListaProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8)
                .addContainerGap())
        );
        panelListaProveedorLayout.setVerticalGroup(
            panelListaProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        buttonGroupTDocProveedor.add(radioButtonCCProveedor);
        radioButtonCCProveedor.setSelected(true);
        radioButtonCCProveedor.setText("C.C");

        buttonGroupTDocProveedor.add(radioButtonNITProveedor);
        radioButtonNITProveedor.setText("NIT");

        buttonGroupTDocProveedor.add(radioButtonOtroProveedor);
        radioButtonOtroProveedor.setText("Otro");

        javax.swing.GroupLayout panelProveedorLayout = new javax.swing.GroupLayout(panelProveedor);
        panelProveedor.setLayout(panelProveedorLayout);
        panelProveedorLayout.setHorizontalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedorLayout.createSequentialGroup()
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProveedorLayout.createSequentialGroup()
                        .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProveedorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DireccionProveedor)
                                    .addComponent(NombreProveedor)
                                    .addComponent(IdProveedor)
                                    .addComponent(CiudadProveedor)
                                    .addComponent(TelefonoProveedor))
                                .addGap(14, 14, 14)
                                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldDireccionProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldIdProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldCiudadProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldTelefonoProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNombreProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NroDocumentoProveedor)
                                    .addComponent(CorreoProveedor)
                                    .addComponent(DepartamentoProveedor)
                                    .addComponent(TipoDocProveedor))
                                .addGap(35, 35, 35)
                                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelProveedorLayout.createSequentialGroup()
                                        .addComponent(radioButtonCCProveedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioButtonNITProveedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioButtonOtroProveedor)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(textFieldCorreoProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(textFieldNroDocProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(textFieldDptoProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                            .addGroup(panelProveedorLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(crearProveedorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(leerProveedorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(actualizarProveedorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(borrarProveedorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelListaProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelProveedorLayout.setVerticalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NombreProveedor)
                        .addComponent(TipoDocProveedor)
                        .addComponent(textFieldNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(radioButtonCCProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButtonNITProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButtonOtroProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionProveedor)
                    .addComponent(NroDocumentoProveedor)
                    .addComponent(textFieldDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNroDocProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdProveedor)
                    .addComponent(CorreoProveedor)
                    .addComponent(textFieldIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CiudadProveedor)
                    .addComponent(DepartamentoProveedor)
                    .addComponent(textFieldCiudadProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDptoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoProveedor)
                    .addComponent(textFieldTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelListaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearProveedorBtn)
                    .addComponent(leerProveedorBtn)
                    .addComponent(actualizarProveedorBtn)
                    .addComponent(borrarProveedorBtn))
                .addGap(52, 52, 52))
        );

        tabbedPanelGestor.addTab("Proveedor", panelProveedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanelGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanelGestor, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteBtnActionPerformed
        String nombre = textFieldNombreCliente.getText();
        String direccion = textFieldDireccionCliente.getText();
        String telefono = textFieldTelefonoCliente.getText();
        String correo = textFieldCorreoCliente.getText();
        String ciudad = textFieldCiudadCliente.getText();
        String departamento = textFieldDepartamentoCliente.getText();
        String nroDocumento = textFieldNroDocumentoCliente.getText();
        String fechaNacimiento = textFieldFechaCliente.getText();
        String id = textFieldIdCliente.getText();
        String tipoDocumento = "";

        if (radioButtonCCCliente.isSelected()) {
            tipoDocumento = "C.C";
        } else if (radioButtonNITCliente.isSelected()) {
            tipoDocumento = "NIT";
        } else if (radioButtonOtroCliente.isSelected()) {
            tipoDocumento = "Otro";
        }

        boolean clienteCreado = false;
        try {
            clienteCreado = controlCliente.crear(nombre, direccion, telefono, correo,
                    ciudad, departamento, tipoDocumento, Integer.parseInt(nroDocumento), fechaNacimiento,
                    Integer.parseInt(id));

            limpiarCampos(1);
            refrescarTabla(1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
        }

        if (clienteCreado) {
            JOptionPane.showMessageDialog(this, "El cliente ha sido creado exitosamente.");
        }
    }//GEN-LAST:event_crearClienteBtnActionPerformed

    private void leerClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerClienteBtnActionPerformed
        try {

            int id = Integer.parseInt((String) modeloTablaCliente.getValueAt(tableCliente.getSelectedRow(), 0));
            String[] matrizDevuelta = controlCliente.buscar(id);

            if (matrizDevuelta != null) {
                textFieldIdCliente.setText(matrizDevuelta[0]);
                textFieldNombreCliente.setText(matrizDevuelta[1]);
                textFieldDireccionCliente.setText(matrizDevuelta[2]);
                textFieldTelefonoCliente.setText(matrizDevuelta[3]);
                textFieldCorreoCliente.setText(matrizDevuelta[4]);
                textFieldCiudadCliente.setText(matrizDevuelta[5]);
                textFieldDepartamentoCliente.setText(matrizDevuelta[6]);
                textFieldNroDocumentoCliente.setText(matrizDevuelta[8]);
                textFieldFechaCliente.setText(matrizDevuelta[9]);
                String tipo = matrizDevuelta[7];
                switch (tipo) {
                    case "C.C" ->
                        radioButtonCCCliente.setSelected(true);
                    case "NIT" ->
                        radioButtonNITCliente.setSelected(true);
                    case "Otro" ->
                        radioButtonOtroCliente.setSelected(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se ha encontrado el cliente.");
                limpiarCampos(1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Rellene el campo ID.");
        }
    }//GEN-LAST:event_leerClienteBtnActionPerformed

    private void actualizarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarClienteBtnActionPerformed

        try {
            int id = Integer.parseInt(textFieldIdCliente.getText());
            String nombre = textFieldNombreCliente.getText();
            String direccion = textFieldDireccionCliente.getText();
            String telefono = textFieldTelefonoCliente.getText();
            String correo = textFieldCorreoCliente.getText();
            String ciudad = textFieldCiudadCliente.getText();
            String departamento = textFieldDepartamentoCliente.getText();
            String nroDocumento = textFieldNroDocumentoCliente.getText();
            String fechaNacimiento = textFieldFechaCliente.getText();
            String tipoDocumento = "";

            if (radioButtonCCCliente.isSelected()) {
                tipoDocumento = "C.C";
            } else if (radioButtonNITCliente.isSelected()) {
                tipoDocumento = "NIT";
            } else if (radioButtonOtroCliente.isSelected()) {
                tipoDocumento = "Otro";
            }

            boolean clienteActualizado = false;
            try {
                clienteActualizado = controlCliente.actualizar(nombre, direccion, telefono, correo,
                        ciudad, departamento, tipoDocumento, Integer.parseInt(nroDocumento), fechaNacimiento,
                        id);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Cliente no existe.");
            }

            if (clienteActualizado) {
                JOptionPane.showMessageDialog(this, "El cliente ha sido actualizado exitosamente.");
            }
            limpiarCampos(1);
            refrescarTabla(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
        }

    }//GEN-LAST:event_actualizarClienteBtnActionPerformed

    private void crearVendedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearVendedorBtnActionPerformed
        String nombre = textFieldNombreVendedor.getText();
        String direccion = textFieldDireccionVendedor.getText();
        String telefono = textFieldTelefonoVendedor.getText();
        String correo = textFieldCorreoVendedor.getText();
        String ciudad = textFieldCiudadVendedor.getText();
        String departamento = textFieldDptoVendedor.getText();
        String nroDocumento = textFieldNroDocVendedor.getText();
        String id = textFieldIdVendedor.getText();
        String tipoDocumento = "";

        if (radioButtonCCVendedor.isSelected()) {
            tipoDocumento = "C.C";
        } else if (radioButtonNITVendedor.isSelected()) {
            tipoDocumento = "NIT";
        } else if (radioButtonOtroVendedor.isSelected()) {
            tipoDocumento = "Otro";
        }

        boolean vendedorCreado = false;
        try {
            vendedorCreado = controlVendedor.crear(nombre, direccion, telefono, correo, ciudad, departamento,
                    tipoDocumento, Integer.parseInt(nroDocumento), Integer.parseInt(id));

            limpiarCampos(2);
            refrescarTabla(2);

            if (vendedorCreado) {
                JOptionPane.showMessageDialog(this, "El vendedor ha sido creado exitosamente.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
        }
    }//GEN-LAST:event_crearVendedorBtnActionPerformed

    private void leerVendedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerVendedorBtnActionPerformed

        try {
            int id = Integer.parseInt((String) modeloTablaVendedor.getValueAt(tableVendedor.getSelectedRow(), 0));
            String[] matrizDevuelta = controlVendedor.buscar(id);
            if (matrizDevuelta != null) {
                textFieldIdVendedor.setText(matrizDevuelta[0]);
                textFieldNombreVendedor.setText(matrizDevuelta[1]);
                textFieldDireccionVendedor.setText(matrizDevuelta[2]);
                textFieldTelefonoVendedor.setText(matrizDevuelta[3]);
                textFieldCorreoVendedor.setText(matrizDevuelta[4]);
                textFieldCiudadVendedor.setText(matrizDevuelta[5]);
                textFieldDptoVendedor.setText(matrizDevuelta[6]);
                textFieldNroDocVendedor.setText(matrizDevuelta[8]);
                String tipo = matrizDevuelta[7];
                switch (tipo) {
                    case "C.C" ->
                        radioButtonCCVendedor.setSelected(true);
                    case "NIT" ->
                        radioButtonNITVendedor.setSelected(true);
                    case "Otro" ->
                        radioButtonOtroVendedor.setSelected(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se ha encontrado el vendedor.");
                limpiarCampos(2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Rellene el campo ID.");
        }
    }//GEN-LAST:event_leerVendedorBtnActionPerformed

    private void actualizarVendedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarVendedorBtnActionPerformed
        try {
            String id = textFieldIdVendedor.getText();
            String nombre = textFieldNombreVendedor.getText();
            String direccion = textFieldDireccionVendedor.getText();
            String telefono = textFieldTelefonoVendedor.getText();
            String correo = textFieldCorreoVendedor.getText();
            String ciudad = textFieldCiudadVendedor.getText();
            String departamento = textFieldDptoVendedor.getText();
            String nroDocumento = textFieldNroDocVendedor.getText();
            String tipoDocumento = "";

            if (radioButtonCCVendedor.isSelected()) {
                tipoDocumento = "C.C";
            } else if (radioButtonNITVendedor.isSelected()) {
                tipoDocumento = "NIT";
            } else if (radioButtonOtroVendedor.isSelected()) {
                tipoDocumento = "Otro";
            }

            boolean vendedorActualizado = false;
            try {
                vendedorActualizado = controlVendedor.actualizar(nombre, direccion, telefono, correo, ciudad, departamento,
                        tipoDocumento, Integer.parseInt(nroDocumento), Integer.parseInt(id));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Vendedor no existe.");
            }

            if (vendedorActualizado) {
                JOptionPane.showMessageDialog(this, "El vendedor ha sido actualizado exitosamente.");
            }
            limpiarCampos(2);
            refrescarTabla(2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos.");
        }
    }//GEN-LAST:event_actualizarVendedorBtnActionPerformed

    public void limpiarCampos(int opcion) {
        //Se limpian los textField

        switch (opcion) {
            case 1 -> {
                textFieldNombreCliente.setText("");
                textFieldDireccionCliente.setText("");
                textFieldTelefonoCliente.setText("");
                textFieldCorreoCliente.setText("");
                textFieldCiudadCliente.setText("");
                textFieldDepartamentoCliente.setText("");
                textFieldNroDocumentoCliente.setText("");
                textFieldIdCliente.setText("");
                textFieldFechaCliente.setText("");
            }
            case 2 -> {
                textFieldNombreVendedor.setText("");
                textFieldDireccionVendedor.setText("");
                textFieldTelefonoVendedor.setText("");
                textFieldCorreoVendedor.setText("");
                textFieldCiudadVendedor.setText("");
                textFieldDptoVendedor.setText("");
                textFieldNroDocVendedor.setText("");
                textFieldIdVendedor.setText("");
            }
            case 3 -> {
                textFieldNombreProveedor.setText("");
                textFieldDireccionProveedor.setText("");
                textFieldTelefonoProveedor.setText("");
                textFieldCorreoProveedor.setText("");
                textFieldCiudadProveedor.setText("");
                textFieldDptoProveedor.setText("");
                textFieldNroDocProveedor.setText("");
                textFieldIdProveedor.setText("");
            }
        }

    }

    /*
    //Método que se encarga de actualizar las lista
    public void refrescarListas(int opcion) {

        //Se define un modelo de lista para almacenar los datos a listar
        DefaultListModel model = new DefaultListModel();

        switch (opcion) {
            case 1:
                for (int i = 0; i < listaClientes.size(); i++) {
                    Cliente cliente = listaClientes.get(i);
                    model.add(i, cliente.toString());
                }
                //listCliente.setModel(model);
                break;
            case 2:
                for (int i = 0; i < listaVendedores.size(); i++) {
                    Vendedor vendedor = listaVendedores.get(i);
                    model.add(i, vendedor.toString());
                }
            //listVendedor.setModel(model);
        }
    }
     */
    public void setModeloTablas() {

//        String[] cabeceraCliente = {"Id", "Nombre", "Direccion", "Telefono", "Correo", "Ciudad", "Departamento",
//            "Tipo Documento", "No. Documento", "Fecha de Nacimiento"};
//        modeloTablaCliente.setColumnIdentifiers(cabeceraCliente);
//        String[][] matrizClientes = controlCliente.refrescarTablaCliente();
//        
//        modeloTablaCliente.setDataVector(matrizClientes, cabeceraCliente);
//        
//        tableCliente.setModel(modeloTablaCliente);

        /*
        

        
        para buscar un item seleccionado de la tabla 
        lista.getSelectedItem().toString();
        getSelectedIndex()7

        String codigo = (String) modelo.getValueAt(tabla.getSelectedRow(), 0);
         */
//        String[] cabeceraVendedor = {"Id", "Nombre", "Direccion", "Telefono", "Correo", "Ciudad", "Departamento",
//            "Tipo Documento", "No. Documento"};
//        modeloTablaVendedor.setColumnIdentifiers(cabeceraVendedor);
//        tableVendedor.setModel(modeloTablaVendedor);
        String[] cabeceraProveedor = {"Id", "Nombre", "Direccion", "Telefono", "Correo", "Ciudad", "Departamento",
            "Tipo Documento", "No. Documento"};
        modeloTablaProveedor.setColumnIdentifiers(cabeceraProveedor);
        tableProveedor.setModel(modeloTablaProveedor);

    }

    public void refrescarTabla(int opcion) {

        switch (opcion) {
            case 1 -> {
                //Se establecen los elementos de la cabecera de la tabla
                String[] cabeceraCliente = {"Id", "Nombre", "Direccion", "Telefono", "Correo", "Ciudad", "Departamento",
                    "Tipo Documento", "No. Documento", "Fecha de Nacimiento"};
                //Se recogen los datos de los clientes añadidos en el almacenamiento temporal
                String[][] matrizClientes = controlCliente.refrescarTablaCliente();
                //Se agregan los datos y la cabecera de la tabla al modelo
                modeloTablaCliente.setDataVector(matrizClientes, cabeceraCliente);
                //Se agrega el modelo a la vista
                tableCliente.setModel(modeloTablaCliente);
            }
            case 2 -> {
                String[] cabeceraVendedor = {"Id", "Nombre", "Direccion", "Telefono", "Correo", "Ciudad", "Departamento",
                    "Tipo Documento", "No. Documento"};
                String[][] matrizVendedores = controlVendedor.refrescarTablaVendedor();
                modeloTablaVendedor.setDataVector(matrizVendedores, cabeceraVendedor);
                tableVendedor.setModel(modeloTablaVendedor);
            }
            case 3 -> {
                Object[] datosProveedor = new Object[modeloTablaProveedor.getColumnCount()];
                modeloTablaProveedor.setRowCount(0);
                for (Proveedor proveedor : tablaProveedores) {
                    datosProveedor[0] = proveedor.getIdProveedor();
                    datosProveedor[1] = proveedor.getNombre();
                    datosProveedor[2] = proveedor.getDireccion();
                    datosProveedor[3] = proveedor.getTelefono();
                    datosProveedor[4] = proveedor.getCorreo();
                    datosProveedor[5] = proveedor.getCiudad();
                    datosProveedor[6] = proveedor.getDepartamento();
                    datosProveedor[7] = proveedor.getTipoDocumento();
                    datosProveedor[8] = proveedor.getNroDocumento();
                    modeloTablaProveedor.addRow(datosProveedor);
                }
                tableProveedor.setModel(modeloTablaProveedor);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadCliente;
    private javax.swing.JLabel CiudadProveedor;
    private javax.swing.JLabel CiudadVendedor;
    private javax.swing.JLabel CorreoCliente;
    private javax.swing.JLabel CorreoProveedor;
    private javax.swing.JLabel CorreoVendedor;
    private javax.swing.JLabel DepartamentoCliente;
    private javax.swing.JLabel DepartamentoProveedor;
    private javax.swing.JLabel DepartamentoVendedor;
    private javax.swing.JLabel DireccionCliente;
    private javax.swing.JLabel DireccionProveedor;
    private javax.swing.JLabel DireccionVendedor;
    private javax.swing.JLabel FechaNacimientoCliente;
    private javax.swing.JLabel IdCliente;
    private javax.swing.JLabel IdProveedor;
    private javax.swing.JLabel IdVendedor;
    private javax.swing.JLabel NombreCliente;
    private javax.swing.JLabel NombreProveedor;
    private javax.swing.JLabel NombreVendedor;
    private javax.swing.JLabel NroDocumentoCliente;
    private javax.swing.JLabel NroDocumentoProveedor;
    private javax.swing.JLabel NroDocumentoVendedor;
    private javax.swing.JLabel TelefonoCliente;
    private javax.swing.JLabel TelefonoProveedor;
    private javax.swing.JLabel TelefonoVendedor;
    private javax.swing.JLabel TipoDocCliente;
    private javax.swing.JLabel TipoDocProveedor;
    private javax.swing.JLabel TipoDocVendedor;
    private javax.swing.JButton actualizarClienteBtn;
    private javax.swing.JButton actualizarProveedorBtn;
    private javax.swing.JButton actualizarVendedorBtn;
    private javax.swing.JButton borrarClienteBtn;
    private javax.swing.JButton borrarProveedorBtn;
    private javax.swing.JButton borrarVendedorBtn;
    private javax.swing.ButtonGroup buttonGroupTDocCliente;
    private javax.swing.ButtonGroup buttonGroupTDocProveedor;
    private javax.swing.ButtonGroup buttonGroupTDocVendedor;
    private javax.swing.JButton crearClienteBtn;
    private javax.swing.JButton crearProveedorBtn;
    private javax.swing.JButton crearVendedorBtn;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton leerClienteBtn;
    private javax.swing.JButton leerProveedorBtn;
    private javax.swing.JButton leerVendedorBtn;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelListaCliente;
    private javax.swing.JPanel panelListaProveedor;
    private javax.swing.JPanel panelListaVendedor;
    private javax.swing.JPanel panelProveedor;
    private javax.swing.JPanel panelVendedor;
    private javax.swing.JRadioButton radioButtonCCCliente;
    private javax.swing.JRadioButton radioButtonCCProveedor;
    private javax.swing.JRadioButton radioButtonCCVendedor;
    private javax.swing.JRadioButton radioButtonNITCliente;
    private javax.swing.JRadioButton radioButtonNITProveedor;
    private javax.swing.JRadioButton radioButtonNITVendedor;
    private javax.swing.JRadioButton radioButtonOtroCliente;
    private javax.swing.JRadioButton radioButtonOtroProveedor;
    private javax.swing.JRadioButton radioButtonOtroVendedor;
    private javax.swing.JTabbedPane tabbedPanelGestor;
    private javax.swing.JTable tableCliente;
    private javax.swing.JTable tableProveedor;
    private javax.swing.JTable tableVendedor;
    private javax.swing.JTextField textFieldCiudadCliente;
    private javax.swing.JTextField textFieldCiudadProveedor;
    private javax.swing.JTextField textFieldCiudadVendedor;
    private javax.swing.JTextField textFieldCorreoCliente;
    private javax.swing.JTextField textFieldCorreoProveedor;
    private javax.swing.JTextField textFieldCorreoVendedor;
    private javax.swing.JTextField textFieldDepartamentoCliente;
    private javax.swing.JTextField textFieldDireccionCliente;
    private javax.swing.JTextField textFieldDireccionProveedor;
    private javax.swing.JTextField textFieldDireccionVendedor;
    private javax.swing.JTextField textFieldDptoProveedor;
    private javax.swing.JTextField textFieldDptoVendedor;
    private javax.swing.JTextField textFieldFechaCliente;
    private javax.swing.JTextField textFieldIdCliente;
    private javax.swing.JTextField textFieldIdProveedor;
    private javax.swing.JTextField textFieldIdVendedor;
    private javax.swing.JTextField textFieldNombreCliente;
    private javax.swing.JTextField textFieldNombreProveedor;
    private javax.swing.JTextField textFieldNombreVendedor;
    private javax.swing.JTextField textFieldNroDocProveedor;
    private javax.swing.JTextField textFieldNroDocVendedor;
    private javax.swing.JTextField textFieldNroDocumentoCliente;
    private javax.swing.JTextField textFieldTelefonoCliente;
    private javax.swing.JTextField textFieldTelefonoProveedor;
    private javax.swing.JTextField textFieldTelefonoVendedor;
    // End of variables declaration//GEN-END:variables
}
